### PR TITLE
add thread_id and message_id to basic message response and callbacks

### PR DESCRIPTION
**Pull request by brianorwhatever**

### CODE REVIEW

**Comment by swcurran** [comment]
Brian -- can you add DCO signoff (using the "-s" option on the commits).  Click on the "Details" link related to DCO to see what is needed at minimum.  All commits must be done with a "commit -s" option.

DCO - Developer Certificate of Origin - https://github.com/apps/dco

**Comment by WadeBarnes** [comment]
It appears this PR may contain changes from other branches that are not ready to be merged into master.  @brianorwhatever could you review the commit history on this PR and ensure it contains the changes you expect to be submitting and that the PR is targeted to the correct branch.

**Review by ianco — CHANGES_REQUESTED** [review]
As Wade mentions it looks like this PR is pulling in unrelated changes

**Comment by brianorwhatever** [comment]
I'll close this as it's no longer important. Sorry!

**Pull request closed without merging**
