### PR TITLE
feature/per tenant settings

### PR DESCRIPTION
**Pull request by amanji**
- Adds `--emit-did-peer-{2 | 4}` per tenant setting
- Adds `--preserve-exchange-records` per tenant setting
- Adds  `--requests-through-public-did` per tenant setting

Resolves: #2724 
Resolves: #2648
Resolves: #2572

### CODE REVIEW

**Comment by swcurran** [comment]
Did any other work get done on this that would be worth documenting?  Other than simply adding the lines, was anything else done that might help future per tenant setting additions?

@loneil — does simply adding these items result in them being exposed/updateable in Traction, or is there another PR needed there to add these three settings to expose them in the Traction UI?

Thanks!

**Review by swcurran — APPROVED** [review]

**Comment by loneil** [comment]
They will need a UI addition to add the fields on the settings page is all

**Comment by amanji** [comment]
Should I do a quick PR to add them in traction?

**Comment by amanji** [comment]
> Did any other work get done on this that would be worth documenting?  Other than simply adding the lines, was anything else done that might help future per tenant setting additions?
> 
> 
> 
> @loneil — does simply adding these items result in them being exposed/updateable in Traction, or is there another PR needed there to add these three settings to expose them in the Traction UI?
> 
> 
> 
> Thanks!

Not for this PR. It would be worthwhile exploring refactoring code to wholesale include parameters and create an exclusion list for those that shouldn't be tenant specific. I'd argue that a refactor of the argparse file should be explored to come up with consistent parameter names, etc.

**Comment by loneil** [comment]
> Should I do a quick PR to add them in Traction?

This would be in an RC right? Maybe would have to just wait until the release that includes it is rolled out anyways?

**Comment by jamshale** [comment]
The failing integration test seems to be a fragile test. The same test failed for my recent draft PR.

**Comment by amanji** [comment]
> > Should I do a quick PR to add them in Traction?
> 
> 
> 
> This would be in an RC right? Maybe would have to just wait until the release that includes it is rolled out anyways?

Yeah we can file an issue for now and I'll add it as soon as a new version is released

**Pull request merged**
