### PR TITLE
feat: make design doc for adding w3C vc format support

### PR DESCRIPTION
**Pull request by tra371**
This PR contains one main document:
- `AnoncredsW3CCompatibility.md` - the design document for implementing w3c vc/vp format support

### CODE REVIEW

**Comment by TimoGlastra** [comment]
Cross referencing our design document for AFJ: https://github.com/openwallet-foundation/agent-framework-javascript/discussions/1671

**Comment by dbluhm** [comment]
@tra371 reminder on sign-off messages on all commits! The DCO check details has pretty detailed instructions on how to correct.

**Comment by tra371** [comment]
> @tra371 reminder on sign-off messages on all commits! The DCO check details has pretty detailed instructions on how to correct. We don't have remediation commits enabled on this repo so the empty commit for DCO will not satisfy the check, unfortunately.

yes, i'll fix them in the next few hours. thank you for reminding..

**Comment by tra371** [comment]
i'm gonna close this PR and create a new one and request your reviews there. @TimoGlastra @dbluhm
sorry about jumping around.

**Pull request closed without merging**
