### PR TITLE
demo uses v2 protocols, not v1

### PR DESCRIPTION
**Pull request by sklump**
Signed-off-by: sklump <srklump@hotmail.com>

### CODE REVIEW

**Comment by sklump** [comment]
@ianco any idea why the integration tests would fail? Is there some magic hook on the other side that needs 0036, 0037 instead of 0453, 0454?

**Comment by sklump** [comment]
Oh - I see there is more. I will get to it today.

**Comment by sklump** [comment]
OK @ianco, good to go now. Thanks for your patience.

**Comment by ianco** [comment]
> OK @ianco, good to go now. Thanks for your patience.

Glad I could help :-D

**Review by ianco — APPROVED** [review]

**Pull request merged**
