### PR TITLE
Fixes for performance demo w/ revocation enabled

### PR DESCRIPTION
**Pull request by andrewwhitehead**
For compatibility with 0.6 updates

### CODE REVIEW

**Review by ianco — DISMISSED** [review]
tested alice/faber working ok

**Review by ianco — CHANGES_REQUESTED** [review]
Alice/faber is ok but I get the following error running `./run_demo performance --revocation`:

`Error: agent Faber has no method handle_issuer_cred_rev to handle webhook on topic issuer_cred_rev`

**Comment by andrewwhitehead** [comment]
@ianco I get that error too, but it doesn't seem to affect the functionality, it's just an ignored webhook.

**Review by ianco — APPROVED** [review]
Reported error is expected

**Comment by ianco** [comment]
> @ianco I get that error too, but it doesn't seem to affect the functionality, it's just an ignored webhook.

Yep you're right it didn't affect the results

**Pull request merged**
