### PR TITLE
Fix: present-proof v2 send-proposal [issue#1474]

### LINKED ISSUE #1474: /present-proof-2.0/send-proposal throws exception on the verifying side
I'm trying to send a indy proof proposal via /present-proof-2.0/send-proposal, as I learned this endpoint now expects a proof request vs the v1 proposal. So to replicate the v1 behavior I'm sending a very specific proof request that describes my intended proposal as close as possible. So this is my payload:

```json
{
    "by_format": {
        "pres_proposal": {
            "indy": {
                "name": "Test V2",
                "version": "2.0",
                "requested_attributes": {
                    "iban": {
                        "name": "iban",
                        "restrictions": [
                            {
                                "schema_id": "M6Mbe3qx7vB4wpZF4sBRjt:2:bank_account:1.0",
                                "cred_def_id": "EraYCDJUPsChbkw7S1vV96:3:CL:571:bob-bank-04",
                                "attr::iban::value": "mytestvalue"
                            }
                        ]
                    }
                },
                "requested_predicates": {}
            }
        }
    }
}
```

This works on the proofing side, but the verifier logs the following exception:

````
2021-11-01 14:42:08,959 aries_cloudagent.core.conductor ERROR Exception in message handler:
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/core/dispatcher.py", line 197, in handle_message
    await handler(context, responder)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/present_proof/v2_0/handlers/pres_proposal_handler.py", line 64, in handle
    comment=context.message.comment,
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/present_proof/v2_0/manager.py", line 135, in create_bound_request
    request_data,
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/present_proof/v2_0/formats/indy/handler.py", line 117, in create_bound_request
    indy_proof_request["name"] = request_data.get("name") or "proof-request"
AttributeError: 'NoneType' object has no attribute 'get'
````

By looking at the handler this kind of makes sense, because the variable that handles the request is assigned as a None type as a default which probably means it is not assigned as intended.

```python
  async def create_bound_request(
        self,
        pres_ex_record: V20PresExRecord,
        request_data: dict = None,
    )
        // ...
        indy_proof_request["name"] = request_data.get("name") or "proof-request"
```

### PR DESCRIPTION
**Pull request by shaangill025**
Signed-off-by: Shaanjot Gill <shaangill025@users.noreply.github.com>

resolve #1474

### CODE REVIEW

**Comment by andrewwhitehead** [comment]
Setting an argument default to an object is generally not a good idea, because each call to the function will receive the same object. I think this method and `create_pres` should default to `None` and handle that appropriately.

**Comment by shaangill025** [comment]
Updated `request_data` dict to default to None for `create_bound_request` and `create_pres` methods.

**Review by andrewwhitehead — APPROVED** [review]

**Comment by swcurran** [comment]
Is the failing test related to this change, or something in the overall flow?

**Comment by swcurran** [comment]
So a configuration error in the integration suite, I gather?  Who can look at this -- @shaangill025, I assume, or perhaps @ianco in the integration suite setup?

**Comment by shaangill025** [comment]
Yes, I think the integration tests have begun failing since PR #1697 merge [includes merged #1676].

**Comment by shaangill025** [comment]
I ran integration tests locally on PR #1675 which was merged 8 days back and I get the same error, looks like an issue with the `ursa-bbs-signatures` package itself.

**Comment by shaangill025** [comment]
I have fixed the `ursa_bbs_signatures._ffi.FfiException.FfiException: Library not found in path: None` error . `ursa-bbs-signatures` `1.0.2` was released yesterday which is when tests started failing. As a temporary fix, I have fixed it to `1.0.1` which is working. But now, `features/steps/0453-issue-credential.py:253` is failing with:
```
7hAries      | 2022-03-30 14:57:36,088 aries_cloudagent.core.event_bus ERROR Error occurred while processing event
7hAries      | Traceback (most recent call last):
7hAries      |   File "/home/indy/aries_cloudagent/revocation/routes.py", line 1090, in on_revocation_registry_event
7hAries      |     max_cred_num=rev_reg_size,
7hAries      |   File "/home/indy/aries_cloudagent/revocation/indy.py", line 45, in init_issuer_registry
7hAries      |     raise RevocationNotSupportedError("Credential definition not found")
7hAries      | aries_cloudagent.revocation.error.RevocationNotSupportedError: Credential definition not found
7hAries      | 
7hAries      | The above exception was the direct cause of the following exception:
7hAries      | 
7hAries      | Traceback (most recent call last):
7hAries      |   File "/home/indy/aries_cloudagent/core/event_bus.py", line 120, in notify
7hAries      |     await processor()
7hAries      |   File "/home/indy/aries_cloudagent/revocation/routes.py", line 1106, in on_revocation_registry_event
7hAries      |     raise RevocationError(e.message) from e
7hAries      | aries_cloudagent.revocation.error.RevocationError: Credential definition not found
```

**Comment by karimStekelenburg** [comment]
I have just deleted the `ursa-bbs-signatures 1.0.2` release from PyPi, so hopefully this resolved the issue.

**Comment by shaangill025** [comment]
@andrewwhitehead No change was made since the last time you approved this. Locking `ursa-bbs-signature` change was reverted as `1.0.2` release was deleted from PyPi.

**Review by ianco — APPROVED** [review]
LGTM

**Pull request merged**
