### PR TITLE
Add by_format to terse webhook for presentations

### PR DESCRIPTION
**Pull request by ianco**
Fix for issue #3065

Note that this is for the 2.0 presentation protocol only, do we need to apply a similar fix for 1.0?

This adds the `by_format` attribute for all webhooks, not just for status `done`, however the demo requires this to work with terse webhooks (and no additional calls to the api endpoints)

Added `by_format` for issue cred as well - was failing in the demo for json-ld :-(

Makes the terse webhooks slightly less terse, but is required if we want the webhook to contain "enough" info for the controller to respond to.

### CODE REVIEW

**Comment by jamshale** [comment]
> @jamshale do you know if it's possible to ignore the SonarCloud error? It doesn't like that we don't explicitly set the user in the demo dockerfile ....

Sonarcloud passing isn't actually required to merge. So we can just ignore this and approve/merge as normal. I don't think there's an easy way to ignore it through the sonarcloud UI.

**Comment by swcurran** [comment]
Is it easy to fix?  Obvs if not, we can leave it — just wondering.

**Comment by ianco** [comment]
> Is it easy to fix? Obvs if not, we can leave it — just wondering.

Prob not difficult to fix but may be time consuming to figure it out.  The dockerfies are all slightly different so we'd need to get them all lined up with each other or figure it out for each one.  I suggest we just log a ticket for now ...

**Comment by ianco** [comment]
The integration test failures are related to json-ld, I'll need to look into it ...

**Review by jamshale — APPROVED** [review]
:+1:

**Review by Gavinok — APPROVED** [review]
Thanks for getting to this so quickly

**Pull request merged**
