### PR TITLE
Patch release 0.12.x

### PR DESCRIPTION
**Pull request by jamshale**
This patches via cherry pick some commits we want in 0.12.x. You can see the commits below. The PRs are as follows.

- #3112
- #3095 
- #3050
- #3010
- #2997 
- #2835
- #2943

The integration tests pipeline doesn't work for patches to branches other than main. We'd need a ticket if we want to support this. For this release I integration tested locally with the @GHA tag and all features passed.

### CODE REVIEW

**Comment by dbluhm** [comment]
Any way we can trigger an AATH run on this branch?

**Comment by swcurran** [comment]
Yes — but only running locally, which I can do if you need.  Edit the [ACA-Py Main Requirements](https://github.com/hyperledger/aries-agent-test-harness/blob/main/aries-backchannels/acapy/requirements-main.txt) file and change the referenced branch to the one to test.

**Comment by swcurran** [comment]
And then — `./manage runset acapy` should do it.

**Comment by dbluhm** [comment]
I haven't run against the AATH yet but I ran the examples in [AME](https://github.com/Indicio-tech/acapy-minimal-example) and the interop tests in [acapy-afj-interop](https://github.com/dbluhm/acapy-afj-interop) and all tests came back looking good.

**Review by dbluhm — APPROVED** [review]
I saw that @jamshale beat me to running AATH against this branch so I'm going to go ahead and approve. This is looking really solid; all tests attempted so far are green.

**Pull request merged**
