### PR TITLE
:arrow_up: Upgrade test and lint dependencies

### PR DESCRIPTION
**Pull request by ff137**
:arrow_up: Upgrades:
- `pytest`: 8.0.0 -> 8.2.0
- `pytest-asyncio`: 0.23.5 -> 0.23.6
- `pytest-cov`: 4.1.0 -> 5.0.0
- `pytest-ruff`: 0.1.1 -> 0.3.2

➖ Removes:
- `mock`
  - This dependency is used to provide unittest.mock features to older version of python
  - Not needed with current python version

___
Edit: additional dependency upgrades from #2940 are pulled in here to speed up merge cycle

Therefore includes:
⬆️ Upgrades:

- `black`: 24.3.0 -> 24.4.2
- `ruff`: 0.1.2 -> 0.4.4
- `pre-commit`: 3.3.3 -> 3.7.1

### CODE REVIEW

**Review by dbluhm — DISMISSED** [review]
LGTM

**Comment by dbluhm** [comment]
Just need a lock file regen but I think these updates are good

**Comment by ff137** [comment]
Not sure why Snyk container is failing. I notice #2951 was recently merged to fix it

**Comment by WadeBarnes** [comment]
> Not sure why Snyk Container is failing. @WadeBarnes I notice #2951 was recently merged to fix it, but for some reason that PR didn't have the Snyk Container job run as part of its checks

Running into the annoying PRs don't have access to secrets and things needing account tokens to work issues again.  Was afraid that was going to happen.  I'll configure the Synk Container job to continue on error until we get it sorted.

**Comment by WadeBarnes** [comment]
> > Not sure why Snyk Container is failing. @WadeBarnes I notice #2951 was recently merged to fix it, but for some reason that PR didn't have the Snyk Container job run as part of its checks
> 
> Running into the annoying PRs don't have access to secrets and things needing account tokens to work issues again. Was afraid that was going to happen. I'll configure the Synk Container job to continue on error until we get it sorted.

Decided to switch the job back to running on push for now.  That way it's running until we can sort things for PRs.
- https://github.com/hyperledger/aries-cloudagent-python/pull/2953

**Comment by ff137** [comment]
@WadeBarnes aah that can be tricky... Thanks! Will rebase once that's in

**Comment by WadeBarnes** [comment]
> @WadeBarnes aah that can be tricky... Thanks! Will rebase once that's in

The update to the Snyk Container job has been merged.

**Pull request merged**
