### PR TITLE
Fix tails_local_path format

### PR DESCRIPTION
**Pull request by DaevMithran**
Signed-off-by: DaevMithran <daevmithran1999@gmail.com>

Issue is not fixed yet. Tried replacing the white spaces with %20 in tails_local_path. I'm not receiving error in swagger now. I'm receiving error in the logs. And it creates only one rev_reg instead of two now. Can anyone guide me on this?

### CODE REVIEW

**Comment by andrewwhitehead** [comment]
You don't want to use %20 in the path everywhere, only when the tails file is actually pushed to the tails server (with `put_file` I believe). In this case it would be best to urlencode the parameter rather than replacing spaces specifically.

**Comment by DaevMithran** [comment]
> You don't want to use %20 in the path everywhere, only when the tails file is actually pushed to the tails server (with `put_file` I believe). In this case it would be best to urlencode the parameter rather than replacing spaces specifically.

Even this did not work. I believe the issue is in indy-tails-server. changing this https://github.com/bcgov/indy-tails-server/blob/main/tails_server/web.py#L135 from os.path.join(storage_path, revocation_reg_id) to os.path.join(storage_path, revocation_reg_id).replace(" ", "\\") might work

**Comment by swcurran** [comment]
Given that it appears the error is in indy-tails-server, should we close this PR and related issues?

**Comment by swcurran** [comment]
Closing this PR.

**Pull request closed without merging**
