### PR TITLE
Duplicate checking for schema and cred def

### PR DESCRIPTION
**Pull request by ianco**
Signed-off-by: Ian Costanzo <ian@anon-solutions.ca>

See issue:  https://github.com/hyperledger/aries-cloudagent-python/issues/1707

### CODE REVIEW

**Review by shaangill025 — APPROVED** [review]

**Comment by TimoGlastra** [comment]
FYI: This PR introduced a breaking change and now broke AATH because AATH tries to recreate the schema. Before ACA-Py would swallow this. Do we need to update this in ACA-Py? Or do we need to change this behaviour in ACA-Py (i.e. not throwing a record, but also not re-creating the schema)


On a side note, it seems to query by the `schema_name` and `schema_version` and throw an error if any records are found. Does that mean if I change my public did and try to create a schema with the same name and version I created with a previous did it will throw an error? I think a schema is unique by name, version, and did.

**Comment by TimoGlastra** [comment]
Created a PR that fixes this in AATH: https://github.com/hyperledger/aries-agent-test-harness/pull/473

**Comment by swcurran** [comment]
I'm not sure I understand why ACA-Py should fail if you try to create the same schema multiple times. Shouldn't it just create the schema if it doesn't exist and continue happily if it does?  AFAIK - the problem previously was that it was creating multiple instances of the same schema (definitely a problem) and returning multiple instances.

On the second point -- I agree in principle that an agent should be allowed to create a schema with the same name but a different DID, since that is permitted on Indy. Not sure how crucial it is though -- it's an "unlikely" situation right now -- but eventually someone will want it...  How big a can of worms does it open if the query includes the public DID for the agent in the check for a schema?

**Comment by ianco** [comment]
Good question about "resource already exists" - I returned an error but other options are available.  I think we should return something that specifies that the resource already exists, though, rather than giving the same result whether the resource was just created or not.  `409` or `303` are options, see https://stackoverflow.com/questions/3825990/http-response-code-for-post-when-resource-already-exists

Regarding the "same schema different did" also a good point, I didn't think about an issuer with multiple DID's.  I don't know if this is a realistic example though (wouldn't there just be a single schema and then multiple cred defs?) but I think the topic of an aca-py agent with multiple public DID's introduces more issues than just this one.

**Pull request merged**
