### PR TITLE
Anoncreds BDD test preparation.

### PR DESCRIPTION
**Pull request by usingtechnology**
Relates to #2297.

This is step one to onboard `anoncreds-rs`. 

Changes to ledger base classes has "broken" schemas and cred defs. This is expected as we are transition. This PR merely allows us to run `BDD` tests, `pytest`, `Flake8` and `black` so we can commit and merge future PRs.

BDD tests that are failing due to anoncreds restructuring of Base ledger are now labelled/tagged: `@GHA-Anoncreds-break`. Fix and reintroduce these tests as needed.

Flake8 class documentation is a placeholder, these have: `TODO: update this docstring - Anoncreds-break.` and should be updated with useful documentation.

Pytests that are broken have been skipped with: `@pytest.mark.skip(reason="Anoncreds-break")`.

Please note that I have added in the `devcontainer` from `main`.

BDD Tests Run:

```
LEDGER_URL=http://test.bcovrin.vonx.io PUBLIC_TAILS_URL=https://tails-test.vonx.io LOG_LEVEL=warning NO_TTY=1 ./run_bdd -t @GHA```

BDD Tests Results:

```
2 features passed, 0 failed, 3 skipped
7 scenarios passed, 0 failed, 57 skipped
37 steps passed, 0 failed, 703 skipped, 0 undefined
```

### CODE REVIEW

**Comment by dbluhm** [comment]
Looks like there's some Indy tests to skip as well.

**Comment by usingtechnology** [comment]
> Looks like there's some Indy tests to skip as well.

Yeah, not evident until it goes through GHA - sigh. Patched in your drop-3.6 work.

**Comment by usingtechnology** [comment]
@dbluhm - had to cherry pick some other commits, BDD tests and pytets run successfully locally, and the GHA tests run successfully.

**Comment by usingtechnology** [comment]
@dbluhm - making progress on the BDD tests (mostly just learning all the bdd infrastructure and where to add/modify things). Got to revocation and hit an issue - Anoncreds revocation only works with the `ghcr.io/indicio-tech/tails-server:sha-3d2feb2` image. So, I can do this locally by standing up an instance but what about when it is run by github actions? Is there an instance deployed that we can use (current GHA use `PUBLIC_TAILS_URL=https://tails-test.vonx.io`)?

How will this affect existing deployments - is there a migration from existing tails servers to this new format? Maybe you have a roadmap already - anyway that is probably for discussions at maintainers meeting.

**Comment by dbluhm** [comment]
Yeah, we would need the changes from https://github.com/bcgov/indy-tails-server/pull/53 merged and deployed to tails-test.vonx.io instance... We should be able to just a local tails server container in the action.

Re: migration, for tails files already published to a tails server, the URL found on the ledger will continue to be valid and resolvable for existing revocation registries. The changes only impact newly created registries that are created through the anoncreds interface specifically. In other words, we should be able to deploy the changes to the tails server now and transition over time on the client side. In other other words, the changes impact only issuers when uploading a tails file for the first time. The holder interacts with the tails server exactly as before.

**Comment by usingtechnology** [comment]
We could go ahead and merge as is. I was working on adding the BDD tests, but those can go in a follow-up PR, and that may take a while as we coordinate the tails server.

**Comment by swcurran** [comment]
@usingtechnology -- the new version of tails-server has been published and is the latest on the main branch. Looks like the ACA-Py tests pick up the main branch, so you should be good to go on the revocation tests.  There is a published container image if you want to use that.

**Comment by usingtechnology** [comment]
That's great... thanks for the update.

**Pull request merged**
