### PR TITLE
Adds support to faber demo for returning json response in connectionless proof-requests

### PR DESCRIPTION
**Pull request by amanji**
Also updates demo to use `WEBHOOK_TARGET`, when supplied, to construct presentation request exchange urls

### CODE REVIEW

**Comment by amanji** [comment]
@ianco @swcurran @WadeBarnes

**Comment by swcurran** [comment]
I'll leave this one to @ianco as I'm not sure how to verify this.

**Comment by ianco** [comment]
Tested on PWD:

1. `$ git clone https://github.com/petridishdev/aries-cloudagent-python.git`
2. `$ cd aries-cloudagent-python/demo`
3. `$ LEDGER_URL=http://test.bcovrin.vonx.io ./run_demo faber --aip 10`

Connected to a BC Wallet and then selected the "connectionless proof request" and got an error:

```
[1/2/3/4/T/X] 2a                                                                                              

#20 Request * Connectionless * proof of degree from alice
Shutting down agent ...
Faber      | 2022-04-11 17:43:30,477 aries_cloudagent.transport.outbound.manager ERROR >>> Error when posting to: http://localhost:8022/webhooks/topic/present_proof/; Error: (<class 'aiohttp.client_exceptions.ClientOSError'>, ClientOSError(None, 'Can not write request body for http://localhost:8022/webhooks/topic/present_proof/'), <traceback object at 0x7f92c8585f08>); Re-queue failed message ...
Faber      | 
Faber      | Shutting down
Faber      | 2022-04-11 17:43:30,964 aries_cloudagent.transport.outbound.manager ERROR Exception in outbound queue processing:
Faber      | concurrent.futures._base.CancelledError: Task was cancelled
Faber      | Process did not terminate in time
ERROR:runners.agent_container:Error terminating agent:
Traceback (most recent call last):
  File "/home/indy/demo/runners/faber.py", line 617, in main
    +f"/pres_req/{pres_req_id}/"
TypeError: bad operand type for unary +: 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/indy/demo/runners/agent_container.py", line 959, in terminate
    await self.agent.terminate()
  File "/home/indy/demo/runners/support/agent.py", line 716, in terminate
    result = await asyncio.wait_for(future, 10, loop=loop)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/indy/demo/runners/support/agent.py", line 703, in _terminate
    raise Exception(msg)
Exception: Process did not terminate in time
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/indy/demo/runners/faber.py", line 778, in <module>
    asyncio.get_event_loop().run_until_complete(main(args))
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
  File "/home/indy/demo/runners/faber.py", line 617, in main
    +f"/pres_req/{pres_req_id}/"
TypeError: bad operand type for unary +: 'str'
[node1] (local) root@192.168.0.28 ~/aries-cloudagent-python/demo
```

**Comment by amanji** [comment]
Formatting error caused by linter

**Review by ianco — APPROVED** [review]
Works like a charm good job!

**Pull request merged**
