### PR TITLE
Apply security patch 0.11.x

### PR DESCRIPTION
**Pull request by jamshale**
Apply security patch to branch 0.11.x
- #3094 

Integration tests currently need to be ran manually on patch releases. I ran all the @GHA tag tests against a local von network and tails server and all 4 features passed.

### CODE REVIEW

**Comment by swcurran** [comment]
Running AATH tests…so far so good.

**Comment by swcurran** [comment]
Very weird. With these changes, all but a set of 7 peer-did tests fail. When I run with 0.11.x branch in ACA-Py a whole bunch more tests fail — coordinate mediation, oob, issue credential and one present proof.  Running again, in case it was a glitch, but local tests are usually pretty reliable…

**Comment by jamshale** [comment]
Interesting. I've only run the integration tests for acapy for this patch. The AATH acapy runset all passed for me for the 0.12.x patch.

**Comment by dbluhm** [comment]
Most of the peer did work wasn't merged until 0.12.0, right? We should expect AATH peer did tests to fail, wouldn't we?

**Comment by jamshale** [comment]
I think that aligns with what tests failed. I kind of expected some failing tests with this branch.

**Review by dbluhm — APPROVED** [review]

**Comment by swcurran** [comment]
Ran the AATH `acapy` runset with this PR, 0.11.x/3.12 and 0.11.x/3.9.  All were consistent, with the same set of tests failing that would be expected — things added after 0.11.x.  However, as noted above, one of the two 0.11.x/3.12 tests had some additional failures — but worked the next time.

I think we’re good with this, and we can go ahead.

Next up will be a PR to publish the patch release.  Stay tuned!

**Pull request merged**
