### PR TITLE
Align Signature decorator with RFC 0234: verkey must be in signers field

### PR DESCRIPTION
**Pull request by jovfer**
`signer` -> `signers`

https://github.com/hyperledger/aries-rfcs/tree/master/features/0234-signature-decorator#tutorial
https://github.com/hyperledger/aries-rfcs/blob/master/features/0234-signature-decorator/ed25519sha256_single.md#application

### CODE REVIEW

**Comment by sklump** [comment]
Correct, but note that signature decorator is itself on the way out.

**Comment by swcurran** [comment]
This change will break compatibility with aries-framework-dotnet unless implemented and deployed together.  Need to think about this, especially since ~sig is going away.

**Comment by sklump** [comment]
The solution may be to change the RFC to fit the implementations, at the risk of a Lighthouse situation: https://en.wikipedia.org/wiki/Lighthouse_and_naval_vessel_urban_legend

**Comment by jovfer** [comment]
The RFCs is updated to avoid not so motivated changes in the implementations
https://github.com/hyperledger/aries-rfcs/pull/298

**Pull request closed without merging**
