### PR TITLE
Address traceability context bug #2743

### PR DESCRIPTION
**Pull request by PatStLouis**
This PR is to address #2743

There is an odd bug that's been ongoing for some time where when trying to expand a did document with the `pyld` library it fails.

Since this happen in a very specific condition, this PR looks to implement a workaround.

When we need to verify a json-ld VC where the issuer/verificationMethod is a `did:web:` scheme, we first manually resolve the did document with the `requests` module, then extract the traceability context form the document if present, then frame the document directly....

Its not pretty, but its the best solution I could come up with that has minimal impact on the existing code. If anyone has a better solution, I'm happy to change it!

@swcurran @dbluhm this is the last critical PR I would like to see in the 0.12 release

### CODE REVIEW

**Comment by dbluhm** [comment]
Not pretty indeed :sweat_smile: I'm quite hesitant on this one. Could you provide some more details on how pyld fails when resolving the traceability context? Has the issue been raised with the authors of that library?

**Comment by PatStLouis** [comment]
So I've raised an issue on the [pyld repo](https://github.com/digitalbazaar/pyld/issues/188) and the traceability [interop repo](https://github.com/w3c-ccg/traceability-interop/issues/613). The `pyld` maintainers never acknowledged the issue and the traceability folks claimed the issue was most likely in the traceability context. There was a [fix suggested](https://github.com/w3c-ccg/traceability-vocab/pull/923) which didn't address the issue. The traceability folks are willing to help however its been difficult to get hold of them. 

For a minimal example, here's a code snippet. Its the specific combination of the traceability context, the traceability service endpoint and type. Remove any one of those 3 and the error isn't raised. 
```
from pyld import jsonld

document = {
  "@context": [
    "https://www.w3.org/ns/did/v1",
    "https://w3id.org/traceability/v1"
  ],
  "service": [
    {
      "id": "did:web:example.com#traceability-api",
      "type": ["TraceabilityAPI"],
      "serviceEndpoint": "https://example.com"
    }
  ]
}

jsonld.expand(document)
```

The issue is with the expanding part, which is a substep of the framing. The error returned is:
```
pyld.jsonld.JsonLdError: ('Tried to nullify a context with protected terms outside of a term definition.',)
Type: jsonld.SyntaxError
Code: invalid context nullification
```

I'm really trying to find a solution here since aca-py currently won't be able to verify `TraceableCredentials` because of this bug. 

There's a traceability meeting tomorrow I will try to get more info but it's been over a month I noticed this issue. It bothers me that nobody else encountered it because as far as I can tell acapy is doing things the right way and not being able to expand a linked data document sounds like a significant issue.

**Comment by dbluhm** [comment]
If I stumbled on the pyld repo and saw that it hadn't seen a commit in 4 years and had 20 open PRs and 50+ issues, I would assume the project was dead. That doesn't seem far from the truth, frankly. A quick scan for an alternative does not yield much in python. So that's too bad lol... Even if we did poke at the library and figure out what needs to be fixed, it seems like it would not help since PRs aren't getting merged.

**Comment by dbluhm** [comment]
I did a bit of `pdb`ing on the example you provided and from a very uninformed perspective, I thin it has to do with the empty `@context` in the `TraceabilityAPI` section of the context

**Comment by dbluhm** [comment]
Can we call step 5.1.1 to the attention of the traceability folks in this section of the json-ld-api spec? https://w3c.github.io/json-ld-api/#algorithm

**Comment by dbluhm** [comment]
Ah, you know what, I think I see the issue:

https://github.com/digitalbazaar/pyld/blob/316fbc2c9e25b3cf718b4ee189012a64b91f17e7/lib/pyld/jsonld.py#L3073

`if not ctx:` should be `if ctx is None:`. `ctx` will be falsey when given an empty dictionary. The algorithm states that the error condition should only be met when the ctx is explicitly a null or, in python, a None.

**Comment by dbluhm** [comment]
I still don't understand the function of the empty context, though. If that's truly necessary according to the traceability context authors then we could try patching the library or putting a PR out for it on the off chance it gets merged (and released....). But if it's not strictly necessary, maybe it could be dropped in a revision of the context.

**Comment by PatStLouis** [comment]
@dbluhm I will try the proposed edit for the pyld library. The maintainers are in the vc-api call I will point this out to them this afternoon and we can get a PR in if it solves the issue. Do you want to author it since you found the solution?

I will also touch on this at the traceability call this afternoon and bring up the point you mentioned.

**Comment by dbluhm** [comment]
> @dbluhm I will try the proposed edit for the pyld library. The maintainers are in the vc-api call I will point this out to them this afternoon and we can get a PR in if it solves the issue. Do you want to author it since you found the solution?
> 
> I will also touch on this at the traceability call this afternoon and bring up the point you mentioned.

Feel free to open the PR! I have no preference to being the author of the solution :slightly_smiling_face:

**Comment by PatStLouis** [comment]
@dbluhm see this [PR](https://github.com/digitalbazaar/pyld/pull/189) for the solution

**Comment by swcurran** [comment]
@PatStLouis — can we close this with the new #2795 change?

**Comment by swcurran** [comment]
Sorry for the extra question — I had been looking at the open PRs in prep for the release candidate and didn’t see your comment on #2795.  Doh!

**Comment by PatStLouis** [comment]
@swcurran Yes when #2795 is merged we won't need this PR as this was a less desirable workaround. The other PR will address the core issue directly.

**Pull request closed without merging**
