### PR TITLE
0.7.5 Cherry Picks

### PR DESCRIPTION
**Pull request by frostyfrog**
These are the cherry picks for Milestone 0.7.5 https://github.com/hyperledger/aries-cloudagent-python/milestone/6
- [X] https://github.com/hyperledger/aries-cloudagent-python/pull/1881 (Already Merged into https://github.com/hyperledger/aries-cloudagent-python/tree/hotfix/0.7.5)
- [x] https://github.com/hyperledger/aries-cloudagent-python/pull/1940
- [X] https://github.com/hyperledger/aries-cloudagent-python/pull/1960
- [x] https://github.com/hyperledger/aries-cloudagent-python/pull/1962

### CODE REVIEW

**Comment by frostyfrog** [comment]
Both #1940 and #1962 appear to have merge conflicts in one form or another. The commits from #1940 made assumptions about work that had been made within other commits (most notably, within the tests.

I moved on to merging #1962, but this appears to have been a mistake. I will switch back to merging #1940 and resolving any merge conflicts before proceeding on with #1962.

**Comment by frostyfrog** [comment]
Force-push due to a commit missing a valid GPG signature

**Review by swcurran — APPROVED** [review]
AATH Tests run with ACA-Py and with AFJ-ACA-Py and all tests passing with 0.7.4 are passing with this branch.  As well, @frostyfrog ran the integration tests and they passed.

**Comment by swcurran** [comment]
@frostyfrog -- we need to cherry pick another PR: #1973 -- a one liner. Could you please do that?  It is updating a dependency for web.py from a git reference to a released version.

@frostyfrog @dbluhm @WadeBarnes -- opinion needed: Assuming this cherry pick goes well, do you think I should do an 0.7.5-rc1 release or would it be safe enough to go straight to 0.7.5 final?

**Comment by WadeBarnes** [comment]
I'd go with an `0.7.5-rc1`.

**Pull request merged**
