### PR TITLE
Handle connection invitations in base64 or URL formats

### LINKED ISSUE #180: Make the Alice agent accept different format invitations
Currently Alice accepts only a JSON plaintext invitation and we'd like her agent to be able to handle other invitation formats.  We'd like this for a demo at the MyData conference on Sept. 25.

Please update the implementation so that Alice can also accept a URL such as:

```
https://agentbook.vonx.io:10000?c_i=eyJyZWNpcGllbnRLZXlzIjogWyJGWGZEaWRjY3E2VlBFeWl4ZTh6ZnVtUUZ5dmN4RzhZRFFoQWVYeUJiYVd6aSJdLCAicm91dGluZ0tleXMiOiBbXSwgInNlcnZpY2VFbmRwb2ludCI6ICJodHRwczovL2FnZW50Ym9vay52b254LmlvOjEwMDAwIiwgImxhYmVsIjogIkFnZW50Qm9vayIsICJAaWQiOiAiYzJkZjAzODgtYWNkNi00NGI0LTlhZDYtNTE5MDlmNmM2MzVhIiwgIkB0eXBlIjogImRpZDpzb3Y6QnpDYnNOWWhNcmpIaXFaRFRVQVNIZztzcGVjL2Nvbm5lY3Rpb25zLzEuMC9pbnZpdGF0aW9uIn0=
```

Or the base64URL encoded argument to the URL:

```
eyJyZWNpcGllbnRLZXlzIjogWyJGWGZEaWRjY3E2VlBFeWl4ZTh6ZnVtUUZ5dmN4RzhZRFFoQWVYeUJiYVd6aSJdLCAicm91dGluZ0tleXMiOiBbXSwgInNlcnZpY2VFbmRwb2ludCI6ICJodHRwczovL2FnZW50Ym9vay52b254LmlvOjEwMDAwIiwgImxhYmVsIjogIkFnZW50Qm9vayIsICJAaWQiOiAiYzJkZjAzODgtYWNkNi00NGI0LTlhZDYtNTE5MDlmNmM2MzVhIiwgIkB0eXBlIjogImRpZDpzb3Y6QnpDYnNOWWhNcmpIaXFaRFRVQVNIZztzcGVjL2Nvbm5lY3Rpb25zLzEuMC9pbnZpdGF0aW9uIn0=
```

### PR DESCRIPTION
**Pull request by andrewwhitehead**
Fixes #180

### CODE REVIEW

**Comment by swcurran** [comment]
@andrewwhitehead - doesn't seem to work with the full URL.  The connection process definitely starts, but I don't get a prompt in the Alice window - it just seems to hang as below:

```
Startup duration: 3.52s
Admin url is at: http://172.17.0.1:8031
Endpoint url is at: http://172.17.0.1:8030

#9 Input faber.py invitation details
Invite details: https://agentbook.vonx.io:10000?c_i=eyJyZWNpcGllbnRLZXlzIjogWyI5N
0p5aXdxcmYzVzdmVzc1NjM3NmJualdYSEdWdlBqc3ZiNGJKNVBnSmtkdyJdLCAicm91dGluZ0tleXMiOi
BbXSwgInNlcnZpY2VFbmRwb2ludCI6ICJodHRwczovL2FnZW50Ym9vay52b254LmlvOjEwMDAwIiwgImx
hYmVsIjogIkFnZW50Qm9vayIsICJAaWQiOiAiZTUxYmY0NmYtY2I2Ny00NDZmLTk4NTYtODEwNDFjMjAz
ODgwIiwgIkB0eXBlIjogImRpZDpzb3Y6QnpDYnNOWWhNcmpIaXFaRFRVQVNIZztzcGVjL2Nvbm5lY3Rpb
25zLzEuMC9pbnZpdGF0aW9uIn0=
Invitation response:
  {
    "updated_at": "2019-09-18 16:43:06.131938Z",
    "initiator": "external",
    "accept": "auto",
    "connection_id": "c1a27f82-7f45-408a-bef1-51609aa9f2d6",
    "routing_state": "none",
    "my_did": "LZCjHp318jcaXgiZpZK9iV",
    "invitation_mode": "once",
    "invitation_key": "97Jyiwqrf3W7fW756376bnjWXHGVvPjsvb4bJ5PgJkdw",
    "created_at": "2019-09-18 16:43:06.088715Z",
    "their_label": "AgentBook",
    "request_id": "adf2dfcf-272d-4dcf-bd0f-205f44b6dba1",
    "state": "request"
  }


```

**Comment by swcurran** [comment]
Same behaviour if I just copy the base64 encoded text:

```
eyJyZWNpcGllbnRLZXlzIjogWyI5N0p5aXdxcmYzVzdmVzc1NjM3NmJualdYSEdWdlBqc3ZiNGJKNVBnSmtkdyJdLCAicm91dGluZ0tleXMiOiBbXSwgInNlcnZpY2VFbmRwb2ludCI6ICJodHRwczovL2FnZW50Ym9vay52b254LmlvOjEwMDAwIiwgImxhYmVsIjogIkFnZW50Qm9vayIsICJAaWQiOiAiZTUxYmY0NmYtY2I2Ny00NDZmLTk4NTYtODEwNDFjMjAzODgwIiwgIkB0eXBlIjogImRpZDpzb3Y6QnpDYnNOWWhNcmpIaXFaRFRVQVNIZztzcGVjL2Nvbm5lY3Rpb25zLzEuMC9pbnZpdGF0aW9uIn0=
```

**Comment by andrewwhitehead** [comment]
@swcurran Is your Alice agent routable?

**Comment by swcurran** [comment]
@andrewwhitehead - don't know - I'm just using the "run_demo alice" on the ACA-Py side. I just know that what worked last week with Agentbook does not work now.  Last week, I had to decode the URL to grab the JSON invite, but once I did that, everything worked.  Now it hangs as noted above.

**Comment by swcurran** [comment]
FYI - same behaviour as last week (using the base64url decoded JSON data) fails as well - no connection established.  This is the data I used:

```jsonc
{"recipientKeys": ["3KwBC89e7WNhPMJDe3WvyTfrPgJZJt739pTm5hD2a8Tw"], "routingKeys": [], "serviceEndpoint": "https://agentbook.vonx.io:10000", "label": "AgentBook", "@id": "51779334-5df9-4307-b56b-7b61d98891d6", "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/connections/1.0/invitation"}
```

**Pull request merged**
