### PR TITLE
@context and type check before issuing W3C cred

### LINKED ISSUE #1568: JSON-ld contexts are not handled correctly
While issuing JSON-LD credentials we have come up with an issue which I also replicated in the [demo](https://github.com/acuderman/aries-cloudagent-python/pull/4):

- If the credential has been issued for the specific type, all of the following requests can use It, independently of the context. In the demo, this is [the second credential](https://github.com/acuderman/aries-cloudagent-python/pull/4/files#diff-4483fbdd64e5a2b502ece2d4c01bbdea683025c1d0eaa9b34146738a2fd16b66R199), where the [passport context](https://ssi.globalid.dev/v1/schema-registry/contexts/Passport/versions/3) does not include ˙Driving license` type, but the credential is still issued without any errors.
- Sometimes only credentials for one context can be issued. Example
  - Issue credential with `https://ssi.globalid.dev/v1/schema-registry/contexts/Driving%20license/versions/2` context -> OK
  - Issue credential with `https://ssi.globalid.dev/v1/schema-registry/contexts/Passport/versions/2` context -> Fails with all attributes dropped error.
 I can not reproduce the second issue with the demo, but the first one can be reproduced and might be connected.

### Reproduction steps
- Clone changes in the [PR](https://github.com/acuderman/aries-cloudagent-python/pull/4)
- Run demo agents:
```
./run_demo faber --did-exchange --cred-type json-ld --wallet-type askar
./run_demo alice --wallet-type askar
```
- Select the issue credential option 2 times (Faber)
- Call fetch w3c credentials endpoint (Alice agent - POST /credentials/w3c)

### Result
- POST /credentials/w3c returns the following result. I left the comments on what is expected.
```
{
  "results": [
    {
      "contexts": [
        "https://www.w3.org/2018/credentials/v1",
        "https://w3id.org/security/bbs/v1",
        "https://ssi.globalid.dev/v1/schema-registry/contexts/Driving%20license/versions/2"
      ],
      "expanded_types": [
        "https://ssi.globalid.dev/v1/schema-registry/contexts/Driving%20license/versions/2#Driving%20license",
        "https://www.w3.org/2018/credentials#VerifiableCredential"
      ],
      "schema_ids": [],
      "issuer_id": "did:key:zUC75D9oXEeUcHiixj8BdzgwsjYcaYi7jRGCdMahqUDRtfXSDkDEXRPuUXTeEU9TSJqFFwaS6nNyWEbfRJe7Y8q3LEcVghsviDJHUx8ohLsigc5RKRxXR5uknv1XSSca3SvnPtp",
      "subject_ids": [
        "did:key:zUC7Lfm5UEUrZxf6CEeLF7WKbqoJD2gBTMeK8oHAYaZmaTG8HUyoV4UW9ZxzFwA9qDBLBc5uXebUtLMCAdYiSrLrK7hvm9pgcXKXV81S7diGYPxjtwHC17jySLLMPfSmTR1RMc7"
      ],
      "proof_types": [
        "BbsBlsSignature2020"
      ],
      "cred_value": {
        "@context": [
          "https://www.w3.org/2018/credentials/v1",
          "https://ssi.globalid.dev/v1/schema-registry/contexts/Driving%20license/versions/2",
          "https://w3id.org/security/bbs/v1"
        ],
        "id": "https://credential.example.com/residents/1234567890",
        "type": [
          "VerifiableCredential",
          "Driving license"
        ],
        "issuer": "did:key:zUC75D9oXEeUcHiixj8BdzgwsjYcaYi7jRGCdMahqUDRtfXSDkDEXRPuUXTeEU9TSJqFFwaS6nNyWEbfRJe7Y8q3LEcVghsviDJHUx8ohLsigc5RKRxXR5uknv1XSSca3SvnPtp",
        "issuanceDate": "2020-01-01T12:00:00Z",
        "credentialSubject": {
          "type": "Driving license",
          "gender_legal": "M",
          "selfie_image": {
            "type": "File",
            "url": "https://example.com",
            "decryption_key": "decryption_key",
            "media_type": "image/png",
            "sha_512_sum": "sha_512_sum"
          },
          "selfie_video": {
            "type": "File",
            "url": "https://example.com",
            "decryption_key": "decryption_key",
            "media_type": "image/png",
            "sha_512_sum": "sha_512_sum"
          },
          "date_of_birth": "1990-10-10",
          "document_number": "10",
          "full_name_legal": "Full name",
          "last_name_legal": "Last name",
          "first_name_legal": "First name",
          "document_front_image": {
            "type": "File",
            "url": "https://example.com",
            "decryption_key": "decryption_key",
            "media_type": "image/png",
            "sha_512_sum": "sha_512_sum"
          },
          "document_date_of_issue": "1992-10-10",
          "document_expiration_date": "2023-10-10",
          "document_country_of_issue": "SI",
          "id": "did:key:zUC7Lfm5UEUrZxf6CEeLF7WKbqoJD2gBTMeK8oHAYaZmaTG8HUyoV4UW9ZxzFwA9qDBLBc5uXebUtLMCAdYiSrLrK7hvm9pgcXKXV81S7diGYPxjtwHC17jySLLMPfSmTR1RMc7"
        },
        "proof": {
          "type": "BbsBlsSignature2020",
          "proofPurpose": "assertionMethod",
          "verificationMethod": "did:key:zUC75D9oXEeUcHiixj8BdzgwsjYcaYi7jRGCdMahqUDRtfXSDkDEXRPuUXTeEU9TSJqFFwaS6nNyWEbfRJe7Y8q3LEcVghsviDJHUx8ohLsigc5RKRxXR5uknv1XSSca3SvnPtp#zUC75D9oXEeUcHiixj8BdzgwsjYcaYi7jRGCdMahqUDRtfXSDkDEXRPuUXTeEU9TSJqFFwaS6nNyWEbfRJe7Y8q3LEcVghsviDJHUx8ohLsigc5RKRxXR5uknv1XSSca3SvnPtp",
          "created": "2021-12-20T11:31:09.964294+00:00",
          "proofValue": "t5Efuv0lbNfasMYfvzL0NgTt64w9KTkplOuFX9ZhHKsXc2+A/bnlAfc4joMbCocyXFpi6SElk3ma+2q+NH3vVftopXOlgr6hStfpfSKkzZRMsOXPD2Hg6VqGR5UBmADm5UhMfAGMPwFYPEPpVJmOsQ=="
        }
      },
      "given_id": "https://credential.example.com/residents/1234567890",
      "cred_tags": {},
      "record_id": "aef4da955e5a4c56b1ef45b95426a268"
    },
    {
      "contexts": [
        "https://www.w3.org/2018/credentials/v1",
        "https://w3id.org/security/bbs/v1",
        "https://ssi.globalid.dev/v1/schema-registry/contexts/Passport/versions/3"
      ],
      "expanded_types": [
        "https://ssi.globalid.dev/v1/schema-registry/contexts/Driving%20license/versions/2#Driving%20license", # -> credential should not be issued successfully as the Passport context does not have `Driving license` type defined.
        "https://www.w3.org/2018/credentials#VerifiableCredential"
      ],
      "schema_ids": [],
      "issuer_id": "did:key:zUC75D9oXEeUcHiixj8BdzgwsjYcaYi7jRGCdMahqUDRtfXSDkDEXRPuUXTeEU9TSJqFFwaS6nNyWEbfRJe7Y8q3LEcVghsviDJHUx8ohLsigc5RKRxXR5uknv1XSSca3SvnPtp",
      "subject_ids": [
        "did:key:zUC7Hk8fzXvLFsicM9GLBrUVHfCPgFiANZ6bewhkJ65AxEQGQmGDFvGP723GfKnQHPnMTpWXQKAJ21cujJQEDtvEcoJYMeWns6qvv7tmP7D2TGxiLVenPqBWWioY3yhihNGK1Nu"
      ],
      "proof_types": [
        "BbsBlsSignature2020"
      ],
      "cred_value": {
        "@context": [
          "https://www.w3.org/2018/credentials/v1",
          "https://ssi.globalid.dev/v1/schema-registry/contexts/Passport/versions/3",
          "https://w3id.org/security/bbs/v1"
        ],
        "id": "https://credential.example.com/residents/1234567890",
        "type": [
          "VerifiableCredential",
          "Driving license"
        ],
        "issuer": "did:key:zUC75D9oXEeUcHiixj8BdzgwsjYcaYi7jRGCdMahqUDRtfXSDkDEXRPuUXTeEU9TSJqFFwaS6nNyWEbfRJe7Y8q3LEcVghsviDJHUx8ohLsigc5RKRxXR5uknv1XSSca3SvnPtp",
        "issuanceDate": "2020-01-01T12:00:00Z",
        "credentialSubject": {
          "type": "Driving license", # -> Should not be issued as the Passport schema does not include "Driving license" type
          "gender_legal": "M",
          "selfie_image": {
            "type": "File",
            "url": "https://example.com",
            "decryption_key": "decryption_key",
            "media_type": "image/png",
            "sha_512_sum": "sha_512_sum"
          },
          "selfie_video": {
            "type": "File",
            "url": "https://example.com",
            "decryption_key": "decryption_key",
            "media_type": "image/png",
            "sha_512_sum": "sha_512_sum"
          },
          "date_of_birth": "1990-10-10",
          "document_number": "10",
          "full_name_legal": "Full name",
          "last_name_legal": "Last name",
          "first_name_legal": "First name",
          "document_front_image": {
            "type": "File",
            "url": "https://example.com",
            "decryption_key": "decryption_key",
            "media_type": "image/png",
            "sha_512_sum": "sha_512_sum"
          },
          "document_date_of_issue": "1992-10-10",
          "document_expiration_date": "2023-10-10",
          "document_country_of_issue": "SI",
          "id": "did:key:zUC7Hk8fzXvLFsicM9GLBrUVHfCPgFiANZ6bewhkJ65AxEQGQmGDFvGP723GfKnQHPnMTpWXQKAJ21cujJQEDtvEcoJYMeWns6qvv7tmP7D2TGxiLVenPqBWWioY3yhihNGK1Nu"
        },
        "proof": {
          "type": "BbsBlsSignature2020",
          "proofPurpose": "assertionMethod",
          "verificationMethod": "did:key:zUC75D9oXEeUcHiixj8BdzgwsjYcaYi7jRGCdMahqUDRtfXSDkDEXRPuUXTeEU9TSJqFFwaS6nNyWEbfRJe7Y8q3LEcVghsviDJHUx8ohLsigc5RKRxXR5uknv1XSSca3SvnPtp#zUC75D9oXEeUcHiixj8BdzgwsjYcaYi7jRGCdMahqUDRtfXSDkDEXRPuUXTeEU9TSJqFFwaS6nNyWEbfRJe7Y8q3LEcVghsviDJHUx8ohLsigc5RKRxXR5uknv1XSSca3SvnPtp",
          "created": "2021-12-20T11:31:15.196076+00:00",
          "proofValue": "qF7iz+dcwCeTbkt8zy2EumByhsEzyMKU9Sa5HdlYThAn8X+VR6+A4YK+FzGv1eupXOLN2d/vRknea2PBsGvHjgDte1VIKQeAWS1hkawvMYUBqZOVI4ZgbNN5SasmSupeDrlyinpKaNqyw18Sfp4uNw=="
        }
      },
      "given_id": "https://credential.example.com/residents/1234567890",
      "cred_tags": {},
      "record_id": "c45663e0d4094ae6b4c2f6a8cb57783c"
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by shaangill025**
Signed-off-by: Shaanjot Gill <gill.shaanjots@gmail.com>
- resolve #1568

### CODE REVIEW

**Comment by shaangill025** [comment]
Hi @TimoGlastra, an issue was reported related to w3c credential issuance, where in a credential with invalid `$.type` will get issued without any error [more details with examples can be found in the issue]. Even though the `document_loader` is working correctly and loads the correct context, the credential when expanded [`jsonld.expand(cred_dict)`] includes invalid `expanded_type`. In this PR, I have implemented a check to stop issuance in such scenarios. I will appreciate your feedback.

**Comment by TimoGlastra** [comment]
I think this approach won't work for all cases.

Although common, not all expanded types will contain an `#` appended to the url to indicate a specific type.


E.g. look at the expanded type in https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%22https%3A%2F%2Fschema.org%22%2C%22%40type%22%3A%22Person%22%7D

The following JSON

```json
{
  "@context": "https://schema.org",
  "@type": "Person"
}
```

expands to

```json
[
  {
    "@type": [
      "http://schema.org/Person"
    ]
  }
]
```

**Comment by TimoGlastra** [comment]
@shaangill025 see my issue in #1568, this is an issue with Pyld and I think the fix you applied here works only for a very specific use case. If someone uses other type url formats it won't work.

I'm not sure why it caches the result as a type and uses that we another document is missing a certain type, but I think we should try to fix this on a lower level

**Comment by shaangill025** [comment]
> @shaangill025 see my issue in #1568, this is an issue with Pyld and I think the fix you applied here works only for a very specific use case. If someone uses other type url formats it won't work.
> 
> I'm not sure why it caches the result as a type and uses that we another document is missing a certain type, but I think we should try to fix this on a lower level

Thanks for taking a look into this.

**Pull request closed without merging**
