### PR TITLE
Anoncreds rs merge from main up to the latest

### PR DESCRIPTION
**Pull request by ianco**
Merge from main up to the point that poetry and ruff are added (commit 9fc598ffe2c406397b30484cb1aa37d6df8ff1cc - see branch https://github.com/ianco/aries-cloudagent-python/tree/ruff_updates_pre)

See comment in issue #2567

Also merged up to the latest code from main and did a bit of cleanup, there are still some test errors ...

### CODE REVIEW

**Comment by ianco** [comment]
This PR has a few failing tests, but overall cleans up most of the differences between the main and anoncreds-rs branch (pulls all updates into the anoncreds-rs branch and updates the ruff formatting)

After this PR is merged there will be about ~100 files that differ between the 2 branches.

**Comment by ianco** [comment]
Status - the `./scripts/run_tests` runs cleanly, however `./scripts/run_tests_indy` doesn't run at all.

The docker images builds and when the tests run it gets the following error:

`E   importlib.metadata.PackageNotFoundError: aries-cloudagent`

Not sure what's going on, I suspect the `poetry install` is installing code somewhere and then `poetry run` is looking for the code somewhere else ...

@dbluhm can you take a look?  I've compared the docker scripts in the various branches and can't tell what's going wrong ...

**Comment by dbluhm** [comment]
@ianco looking at the GHA run of the tests, I didn't see the ImportError you mentioned; has this been resolved with your most recent push?

**Comment by ianco** [comment]
@dbluhm  I get the error running locally.  If I run `./scripts/run_tests` everything runs fine but if I run `./scripts/run_tests_indy` then I get the error.  (Both run fine in both the `main` and the current `anoncreds-rs` branch).

The GHA just runs `poetry run pytest` it doesn't use either of these scripts.

**Comment by usingtechnology** [comment]
i'm also getting it locally, seeing if I can figure it out. complicated dockerfile!

**Comment by ianco** [comment]
OK it may be happening on `main` as well, I ran a quick test and just got the same error on `main`, I'm just doing a docker purge and re-testing again

**Comment by ianco** [comment]
OK confirmed I get the same error in `main`.  Since the whole purpose was to build a dockerfile including indy-sdk and run the relevant tests - and we're ending support for indy-sdk - I suggest we ignore the error.

We'll need to review the tests to make sure we're running the full set of tests in GHA (and not just the non-indy-flagged tests).

**Comment by usingtechnology** [comment]
@ianco 
in `Dockerfile.indy`, change line the `acapy-test` image (line 179). The change is to copy over the aries_cloudagent source and tell poetry to install it all. We need the source directory on the image for a "full" poetry install.

```
# ACA-Py Test
# Used to run ACA-Py unit tests with Indy
FROM indy-base as acapy-test

USER indy

RUN mkdir src test-reports

WORKDIR /home/indy/src

RUN mkdir -p test-reports && chown -R indy:indy test-reports && chmod -R ug+rw test-reports

ADD ./README.md pyproject.toml ./poetry.lock ./
COPY ./aries_cloudagent/ ./aries_cloudagent/

USER root
RUN pip install --no-cache-dir poetry
RUN poetry install --no-directory -E "askar bbs indy"

ADD --chown=indy:root . .
USER indy

ENTRYPOINT ["/bin/bash", "-c", "poetry run pytest \"$@\"", "--"]
```

**Comment by andrewwhitehead** [comment]
@usingtechnology  Sounds like that fix might need to be added to the main branch?

**Review by andrewwhitehead — APPROVED** [review]

**Pull request merged**
