### PR TITLE
Add explicit write permission to publish workflow

### PR DESCRIPTION
**Pull request by jamshale**
This should fix the publish workflows. Worked with my forked repo.

### CODE REVIEW

**Review by swcurran — APPROVED** [review]

**Comment by jamshale** [comment]
@swcurran  This didn't work in this repo. I think there is organizational settings that need to be changed.

**Comment by swcurran** [comment]
@ryjones — can you help with this?   @WadeBarnes — anything you can help with here?

**Comment by jamshale** [comment]
image

Just need to change these settings.

**Comment by swcurran** [comment]
That option is grayed out for me, so I can’t change it.

**Comment by jamshale** [comment]
@WadeBarnes

**Comment by WadeBarnes** [comment]
Grayed out for me too.

**Pull request merged**
