### PR TITLE
fix: mediation routing keys as did key

### LINKED ISSUE #2357: Mediation webhook routing keys aren't did:keys
Just about everywhere else, in the coordinate mediation protocol and manager, we're now handling routing and recipient keys in did:key format. However, webhooks with topic `mediation` still have routing keys reported as raw base58 encoded public keys. This is occurring at least on the mediation client side.

### LINKED ISSUE #2492: Routing keys for public DIDs should be published as did:keys
When using a mediator, routing keys are published in the same attrib transaction that includes the service endpoint of the mediator. Those routing keys are currently being published as base58 encoded values. They should be did:keys.

Example: https://indyscan.indiciotech.io/tx/IND_TESTNET/domain/15635

### PR DESCRIPTION
**Pull request by dbluhm**
This PR is a minor rethink to #2502; as discussed in my comment on that PR, I think I/we went a bit too far with base58 to did:key normalization. This is the minimum set of changes required to fix the two issues.

Fixes #2492.
Fixes #2357.

These changes also cause did:keys to be sent out in mediation grant messages and, subsequently, connections/did exchange as the `routingKeys` in the DID Document. This has interop implications. A big motivator for these changes however is to enable AFJ/Bifold based agents to connect through a public DID with mediation where AFJ/Bifold is expecting did:keys in the routing keys in the endpoint attrib. So this should help push us towards "good" interop and should only break "bad" interop.

**Updates:** This PR has evolved. Here is the current state of the changes.

- Coordinate Mediation protocol will accept either base58 or did:key (this was already implemented)
- Coordinate Mediation protocol will emit did:key (this was already implemented)
- Coordinate Mediation protocol manager will store the routing keys as did:key values. This is the critical new stuff that solves the issues linked above.
- Connections protocol will accept any of base58, did:key, or did:key refs encoded routingKeys (this was already implemented and recently augmented by #2537).
- Connections protocol will emit base58 encoded routingKeys (for legacy support).
- DID Exchange will accept any of base58, did:key, or did:key ref encoded routingKeys (this was already implemented and recently augmented by #2537).
- DID Exchange will emit did:key ref encoded routingKeys (this is new).
- OOB will accept either did:key or did:key ref encoded routingKeys (this is new).
- OOB will emit did:key ref encoded routingKeys for inline services (this is new).

### CODE REVIEW

**Review by usingtechnology — APPROVED** [review]
LGTM

**Comment by dbluhm** [comment]
I've got some integration test issues to sort out.

**Comment by usingtechnology** [comment]
> I've got some integration test issues to sort out.

Ok,  that's good to hear actually. My run of BDD wasn't working (hanging?) but I figured you had run them and that it was just my machine acting up (as it did earlier today) and figured it was time for a reboot. I'll cancel the review/approval and try running BDD after your updates.

**Comment by dbluhm** [comment]
A new development: given our recent tightening up of DID Doc semantics and using PyDID to interact with DID Documents, it came to my attention that we were out of spec with the `routingKeys` values we were sending and accepting previously. Old validation required `did:key`s without a fragment. The only place we really call out what we're expecting in routingKeys is in [the OOB RFC under the description for the services](https://github.com/hyperledger/aries-rfcs/blob/main/features/0434-outofband/README.md#the-services-item). The text says that they should be DID key references but the examples show just `did:key`s. It is also mentioned in the [DID Doc conventions RFC](https://github.com/hyperledger/aries-rfcs/blob/main/features/0067-didcomm-diddoc-conventions/README.md#service-conventions).

This might present an interop challenge. I'll see if I can check in with AFJ's DID Exchange/OOB implementation and see what it is expecting.

**Comment by dbluhm** [comment]
My investigation suggests that AFJ will accept either a DID Key or a DID Key reference.

**Comment by usingtechnology** [comment]
Ran changes locally...BDD tests look good by pytests are failing.

**Comment by TimoGlastra** [comment]
> My investigation suggests that AFJ will accept either a DID Key or a DID Key reference. However, it will emit just a DID Key, not a DID Key reference, in OOB invitations but sends references in the DID Docs it forms for DID Exchange...

We ran into this issue in the AFJ implementation of OOB, but as the RFC just used keys (no reference) and ACA-Py's implementation also did that we went for the non-key reference. I think there is an issue somewhere (but it could also be that this was discussed in discord)

**Comment by swcurran** [comment]
FYI -- when I ran the AATH acapy run set, the following two tests fail:

```
Failing scenarios:
  features/0211-coordinate-mediation.feature:50  Request mediation with the mediator accepting the mediation request and creating a connection using the mediator -- @2.1 0160 connection
  features/0211-coordinate-mediation.feature:149  Two agents creating a connection using a mediator with overlapping transports -- @2.1 Acme and Faber creating a 0160 connection using Bob a mediator with overlapping transports
```

To run the specific tests use, update `requirements-main.txt` to use the branch to be merged and then:

`./manage run -d acapy-main -t @T002-RFC0211,@T004-RFC0211,@T005-RFC0211 -t @RFC0160`

Example error from run:

```
     Assertion Failed: FAILED SUB-STEP: And "Faber" receives the connection invitation
      Substep info: Assertion Failed: resp_status 422 is not 200; {"routingKeys": {"0": ["Value did:key:z6MkfDd4T7QAeuLrjeigXe8HfdvqNHWA5KGmMjkrLceE27Bz#z6MkfDd4T7QAeuLrjeigXe8HfdvqNHWA5KGmMjkrLceE27Bz is not a raw Ed25519VerificationKey2018 key"]}}
      Traceback (of failed substep):
        File "/usr/local/lib/python3.7/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/usr/local/lib/python3.7/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/0160-connection.py", line 152, in step_impl
          assert resp_status == 200, f"resp_status {resp_status} is not 200; {resp_text}"
      
      Captured stdout:
      Data table in step contains an unrecognized role 'recipient', must be inviter, invitee, inviteinterceptor, issuer, holder, verifier, prover, requester, responder, mediator, and recipient
      Data table in step contains an unrecognized role 'sender', must be inviter, invitee, inviteinterceptor, issuer, holder, verifier, prover, requester, responder, mediator, and recipient
```

**Comment by dbluhm** [comment]
This PR is now ready for review. I ended up trimming out some additional unused code relating to the previously removed old routing protocol and "inbound connection" handling on the `create_did_doc` method. Also, I cleaned up some items relating to the route managers to further abstract out multi-tenancy from connection protocols.

**Comment by usingtechnology** [comment]
Lots of poking around today and running tests and AATH.
Something on my local dev doesn't like running pytests, but can run `./scripts/run_tests` successfully and that's what counts.

Moving on to AATH... there are issues that we need to address in that repo. 

We need to update `0160-connection.py` to handle `recipient` and `sender` - those are not in the `case/switch` statement so it raises that error when it shouldn't. What I did to bypass this probably isn't proper but it got me further down the call stack to uncover other issues.

Next there is an actual issue with the tests. When there are no inbound transports, the backchannel code doesn't create an endpoint parameter, so we hit an ACA-py config error.

`aries_cloudagent.config.error.ArgsParseError: -e/--endpoint is required`. 

Simple enough to add a default `http` endpoint.

However, then you hit another config error: `aries_cloudagent.config.error.ArgsParseError: -it/--inbound-transport is required`.

I am not sure how this scenario ever ran successfully since the test is to not have inbound transport and for 3 years that configuration has been required. At least from what I can see.

WIth ALL of that being said, this branch/PR does have an issue to address that is uncovered in AATH... routing keys not Ed25519VerificationKey2018.

```
  features/0211-coordinate-mediation.feature:50  Request mediation with the mediator accepting the mediation request and creating a connection using the mediator -- @2.1 0160 connection
```

fails with:

```
      Assertion Failed: FAILED SUB-STEP: And "Faber" receives the connection invitation
      Substep info: Assertion Failed: resp_status 422 is not 200; {"routingKeys": {"0": ["Value did:key:z6MkrSmucdbqKmWhVxJM4q2nyAFD1pCLNrfQWttos4ntoqMj#z6MkrSmucdbqKmWhVxJM4q2nyAFD1pCLNrfQWttos4ntoqMj is not a raw Ed25519VerificationKey2018 key"]}}
      Traceback (of failed substep):
        File "/usr/local/lib/python3.7/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/usr/local/lib/python3.7/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/0160-connection.py", line 152, in step_impl
          assert resp_status == 200, f"resp_status {resp_status} is not 200; {resp_text}"
```


```
  features/0211-coordinate-mediation.feature:149  Two agents creating a connection using a mediator with overlapping transports -- @2.1 Acme and Faber creating a 0160 connection using Bob a mediator with overlapping transports
```

fails with:

```
      Assertion Failed: FAILED SUB-STEP: And "Acme" receives the connection invitation
      Substep info: Assertion Failed: resp_status 422 is not 200; {"routingKeys": {"0": ["Value did:key:z6MkrSmucdbqKmWhVxJM4q2nyAFD1pCLNrfQWttos4ntoqMj#z6MkrSmucdbqKmWhVxJM4q2nyAFD1pCLNrfQWttos4ntoqMj is not a raw Ed25519VerificationKey2018 key"]}}
      Traceback (of failed substep):
        File "/usr/local/lib/python3.7/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/usr/local/lib/python3.7/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/0160-connection.py", line 152, in step_impl
          assert resp_status == 200, f"resp_status {resp_status} is not 200; {resp_text}"
```

**Comment by usingtechnology** [comment]
That seems like a long comment, but think it boils down to a routing keys fix, and we add issues to AATH for some other things.

**Comment by dbluhm** [comment]
Thanks for the testing @usingtechnology! I'll dig into this when I get a chance.

**Comment by dbluhm** [comment]
I'm able to reproduce the issue in my own test environment. Interestingly, it's specific to the connection protocol Admin API. DID Exchange is working fine. Looks like it's a matter of the connection invitation schema being picky about what the routing keys look like.

**Comment by dbluhm** [comment]
@usingtechnology @swcurran this PR is ready for review!

**Comment by dbluhm** [comment]
Yeah, I think another round of testing is appropriate.

**Comment by usingtechnology** [comment]
AATH update requirements-main.txt

```
aries-cloudagent[indy, bbs, askar]@git+https://github.com/hyperledger/aries-cloudagent-python@de09845e4ac32081b2825b448dbb1485c5dbdf5d
acapy-resolver-universal@git+https://github.com/sicpa-dlab/acapy-resolver-universal.git@v0.1.0
```

```
BUILD_AGENTS=acapy-main ./manage build
./manage run -d acapy-main -t @T002-RFC0211,@T004-RFC0211,@T005-RFC0211 -t @RFC0160
```

Still get the errors like:

```
      Assertion Failed: FAILED SUB-STEP: And "Acme" receives the connection invitation
      Substep info: Assertion Failed: resp_status 422 is not 200; {"routingKeys": {"0": ["Value did:key:z6MkfsqtL1nN8Rj94LXBxYXRrbYZfz9kvac4Br3LZkJXRDAr is not a raw Ed25519VerificationKey2018 key"]}}
      Traceback (of failed substep):
        File "/usr/local/lib/python3.7/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/usr/local/lib/python3.7/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/0160-connection.py", line 152, in step_impl
          assert resp_status == 200, f"resp_status {resp_status} is not 200; {resp_text}"
```

**Comment by dbluhm** [comment]
@usingtechnology I think the commit to checkout should be a8cf6ad684892ff49453662b4843509afc63de89

**Comment by swcurran** [comment]
FYI — when I run PR tests in AATH, I update the requirements-main.txt file to:

```
aries-cloudagent[indy, bbs, askar]@git+https://github.com/<user>/aries-cloudagent-python@<branch in user’s fork>
acapy-resolver-universal@git+https://github.com/sicpa-dlab/acapy-resolver-universal.git@v0.1.0
```

So for this one:

```
aries-cloudagent[indy, bbs, askar]@git+https://github.com/dbluhm/aries-cloudagent-python@fix/mediation-routing-keys-as-did-key
acapy-resolver-universal@git+https://github.com/sicpa-dlab/acapy-resolver-universal.git@v0.1.0

```

**Comment by usingtechnology** [comment]
When I use the correct commit hash, all looks good. pytests and AATH all check out. Great work!

**Review by usingtechnology — APPROVED** [review]
👍 👍 - pytests and AATH all check out.

**Pull request merged**
