### PR TITLE
introduce ACAPY_NO_BANNER--no-banner and replace print statements by logging in plugins

### PR DESCRIPTION
**Pull request by rngadam**
see issue #3202

### CODE REVIEW

**Comment by WadeBarnes** [comment]
See my comments here; https://github.com/hyperledger/aries-cloudagent-python/issues/3202#issuecomment-2315548060.  I don't think suppressing deprecation notices is a good idea, it defeats their purpose.

**Review by WadeBarnes — CHANGES_REQUESTED** [review]
See my comments here; https://github.com/hyperledger/aries-cloudagent-python/issues/3202#issuecomment-2315548060. I don't think suppressing deprecation notices is a good idea, it defeats their purpose.

**Comment by rngadam** [comment]
> See my comments here; [#3202 (comment)](https://github.com/hyperledger/aries-cloudagent-python/issues/3202#issuecomment-2315548060). I don't think suppressing deprecation notices is a good idea, it defeats their purpose.
> 
> Regarding the standard ACA-Py startup banner. I think this is a very important piece of diagnostic information that should not be suppressed. It provides you with a summary of the agent configuration and version that can help you identify issues right off the bat.

Outputting the banner is the default. ACAPY_NO_BANNER allows to suppress the banner output in situation where the information in diagnostic is already known to the user.

**Comment by swcurran** [comment]
I've added this to the ACA-Pug meeting coming up this Tuesday, Sept. 3 at 8:00 Pacific / 17:00 Central Europe.  @rngadam -- would you be able to make that?  Details are here: https://wiki.hyperledger.org/display/ARIES/2024-09-03+Aries+Cloud+Agent+-+Python+Users+Group+Community+Meeting

**Comment by jamshale** [comment]
Closing this as won't do. Feel free to re-open it if this is still something you really think is needed.

**Pull request closed without merging**
