### PR TITLE
adjust Aries demo README to fit current admin API

### PR DESCRIPTION
**Pull request by sklump**
re: https://github.com/sklump/aries-cloudagent-python/pull/new/fix-demo-doc-re-mediation

Signed-off-by: sklump <srklump@hotmail.com>

### CODE REVIEW

**Review by ianco — DISMISSED** [review]

**Comment by swcurran** [comment]
It looks to me like there are two empty PNG files in this PR.  Are those supposed to be there?

**Comment by sklump** [comment]
No, those should have content - incoming

**Comment by sklump** [comment]
... update: all .PNG files come up as empty once pushed to the PR.

Does anyone know how to make that not happen?

**Comment by TimoGlastra** [comment]
It seems like the images are not removed but made smaller. Did you regenerate them or made them smaller? See image below

image

**Comment by sklump** [comment]
That's how they render on my box. The github diff says they're empty though. Maybe if I blow them up.

**Review by andrewwhitehead — APPROVED** [review]

**Pull request merged**
