### PR TITLE
Add functionality for building and running agents seprately

### PR DESCRIPTION
**Pull request by sarthakvijayvergiya**
1. Added support for building the agent image using 'build'
2. Implemented the ability to start the agent container with 'start' with host files mounted into docker container
3. Updated the script to handle the 'resolution' command with its options(build & run)

Build
`./demo/run_demo build alice --wallet-type askar-anoncreds --events
`
Run
`./demo/run_demo run alice --wallet-type askar-anoncreds --events
`

### CODE REVIEW

**Comment by swcurran** [comment]
I’m not clear on what you mean by the “resolution” functionality.  I can see the separation of build and run — is that what you mean?

**Comment by sarthakvijayvergiya** [comment]
> I’m not clear on what you mean by the “resolution” functionality. I can see the separation of build and run — is that what you mean?

Yes, the separation of "build" and "run" refers to different functionalities in the script. Specifically, "build" is responsible for building the Docker image of the agent, while "run" executes the agent within a Docker container.

In the "run" functionality, we also mount volumes from the host into the Docker container. This allows for a more streamlined development and debugging process, as we don't need to rebuild the Docker images repeatedly.

Additionally, the script supports a default behavior: if neither "build" nor "run" is specified, it defaults to both building and running the agent.

**Comment by swcurran** [comment]
Got it — sounds good.  Thanks!

**Comment by ianco** [comment]
Looks good!  Can you add a comment to the docs (maybe here: https://github.com/hyperledger/aries-cloudagent-python/blob/main/docs/demo/README.md#other-environment-settings) describing this?  Maybe mention that this can support auto-reloading of code so you don't have to repeatedly restart the demo while developing ...

**Comment by sarthakvijayvergiya** [comment]
> Looks good! Can you add a comment to the docs (maybe here: https://github.com/hyperledger/aries-cloudagent-python/blob/main/docs/demo/README.md#other-environment-settings) describing this? Maybe mention that this can support auto-reloading of code so you don't have to repeatedly restart the demo while developing ...

perfect, I have updated the docs.
Thank you!

**Comment by ianco** [comment]
Hi @sarthakvijayvergiya , ran a quick test and it looks good.

Just to be clear - when I ran the demo and edited the code, the demo didn't auto-reload.  I stopped and restarted the agent (didn't have to rebuild the container) and it picked up the changes.  So it's a more efficient process for sure, but should it auto-reload without restarting?

**Comment by sarthakvijayvergiya** [comment]
> Hi @sarthakvijayvergiya , ran a quick test and it looks good.
> 
> Just to be clear - when I ran the demo and edited the code, the demo didn't auto-reload. I stopped and restarted the agent (didn't have to rebuild the container) and it picked up the changes. So it's a more efficient process for sure, but should it auto-reload without restarting?

Oh yeah Good catch, I haven't implemented auto reloading it was just to mitigating the need for repetitive container builds.

Adding auto-reloading would be a great feature, but it's out of scope for this request. I can work on it in another request.

**Review by ianco — APPROVED** [review]

**Pull request merged**
