### PR TITLE
added some clarifications for environment variable use in ACA-Py

### PR DESCRIPTION
**Pull request by Executioner1939**
Hi @WadeBarnes I made a very quick attempt at some clarifications for Environment Variables, please let me know what you would like me to change or elaborate on.

I always feel it's best to open a PR quickly to get feedback and iterate. I think that `Command Line Parameters` and `Environment Variables` could be nested under the `Configuring ACA-PY` heading.

### CODE REVIEW

**Review by WadeBarnes — CHANGES_REQUESTED** [review]
@Executioner1939, It looks like some of the lines got broken into multiple lines.

Otherwise LGTM

**Comment by Executioner1939** [comment]
@WadeBarnes yes, it seems my IDE formatted the markdown file, should I revert that?

**Comment by WadeBarnes** [comment]
> @WadeBarnes yes, it seems my IDE formatted the markdown file, should I revert that?

Yes, please.

**Comment by swcurran** [comment]
@Executioner1939 — sorry to be a pain, but any contributions have to have a DCO signing/acknowledgement — DCO - Developer Certificate of Origin - https://github.com/apps/dco.  See the “Details” link of the failed “DCO” Check above for how to fix — if you are comfortable with git/github.  If not, you can:

- make a copy of the file you changed,
- get back to the latest “main” branch,
- create a new branch,
- copy the file into that branch,
- make a new commit with the “-s” option (which will sign it for DCO purposes).

If that is too much effort, we can take what you have done and PR it (so the info gets into the repo) — but you won’t get the create for the contribution.

Thanks!

**Comment by swcurran** [comment]
Ping @Executioner1939 -- would love to get this merged, if you can do the update.  I just hit the "Update Base", which probably made doing the DCO update harder --- sorry about that.

**Comment by Executioner1939** [comment]
Hey guys, sorry  I will sort it out tonight :-)

**Comment by Executioner1939** [comment]
Hi @WadeBarnes I created a new PR here: #3028, so we can close this one

**Pull request closed without merging**
