### PR TITLE
[RFC] Do NOT merge yet - Allow access to /ledger/register-nym with multitenancy

### PR DESCRIPTION
**Pull request by matgnt**
The change shows what might be necessary to support "Option 3" described in #1657 

Still needs discussion whether this is the desired way to go.

### CODE REVIEW

**Comment by ianco** [comment]
You can register a nym on the ledger through an endorser.  With PR 1616 you'll also be able to update attrib through an endorser as well

**Comment by chumbert** [comment]
We also considered using the root wallet as endorser but decided against it.

Apart from these endorsement considerations, I'm not in favor of opening any new endpoints. This endorsement design decision, that can make sense for some but not for others, would have an impact on all aca-py instances due to the endpoint whitelist being hardcoded. This was one of the cons when making our decision.

If we want to accommodate for this, I would suggest having the endpoints whitelist be configurable instead of hardcoded. This way, having the root wallet as an endorser can be an option, but the downsides of opening new endpoints  won't impact all multi-tenant aca-py instances.

**Comment by dbluhm** [comment]
With #1836, this type of change should no longer require code changes.

**Comment by matgnt** [comment]
Closing this PR. Thanks @dbluhm for your PR #1836 that should do the trick in a more configurable way.

**Pull request closed without merging**
