### PR TITLE
fix: more resilient checks in verify signed attachments

### LINKED ISSUE #2608: ACA-Py - AFJ: ACA-Py fails on DID Exchange Request
ACA-Py fails on a DID Exchange request from AFJ.

```mermaid
sequenceDiagram
participant acapy as ACA-Py
participant afj as AFJ

acapy ->> acapy: Create OOB invitation
acapy -->> afj: Deliver invitation
afj -x acapy: https://didcomm.org/didexchange/1.0/request
```

OOB Invitaiton received by AFJ:
```json
{
  "@type": "https://didcomm.org/out-of-band/1.1/invitation",
  "@id": "f459945c-39f1-4052-819f-6ef862eb4201",
  "label": "Alice",
  "handshake_protocols": [
    "https://didcomm.org/didexchange/1.0"
  ],
  "services": [
    {
      "id": "#inline",
      "serviceEndpoint": "http://acapy:3000",
      "type": "did-communication",
      "recipientKeys": [
        "did:key:z6MkrwQaATaVCja2XSPwfq1t3ABLvcYW8y58ammmZnYftDEu#z6MkrwQaATaVCja2XSPwfq1t3ABLvcYW8y58ammmZnYftDEu"
      ]
    }
  ]
}
```

Request prepared by AFJ:
```json
{
  "@type": "https://didcomm.org/didexchange/1.0/request",
  "@id": "2e082ac5-c0d2-4fab-b369-27338d51c238",
  "label": "test-agent",
  "did": "did:peer:1zQmd5sQ7mhYcbwtr5L6fQ1KfwFYtEGU3mCpedeBtgmycXC5",
  "~thread": {
    "pthid": "f459945c-39f1-4052-819f-6ef862eb4201"
  },
  "did_doc~attach": {
    "@id": "33718c9b-3f48-4576-8fd3-516fad2409f8",
    "mime-type": "application/json",
    "data": {
      "base64": "eyJAY29udGV4dCI6WyJodHRwczovL3czaWQub3JnL2RpZC92MSJdLCJpZCI6ImRpZDpwZWVyOjF6UW1kNXNRN21oWWNid3RyNUw2ZlExS2Z3Rll0RUdVM21DcGVkZUJ0Z215Y1hDNSIsInNlcnZpY2UiOlt7ImlkIjoiI2lubGluZS0wIiwic2VydmljZUVuZHBvaW50IjoiZGlkY29tbTp0cmFuc3BvcnQvcXVldWUiLCJ0eXBlIjoiZGlkLWNvbW11bmljYXRpb24iLCJwcmlvcml0eSI6MCwicmVjaXBpZW50S2V5cyI6WyIjNzNkMDZhM2ItNzRkNS00ZjlhLWI4YzctZTA3NWNiNzY2NGRkIl0sInJvdXRpbmdLZXlzIjpbXX1dLCJhdXRoZW50aWNhdGlvbiI6W3siaWQiOiIjNzNkMDZhM2ItNzRkNS00ZjlhLWI4YzctZTA3NWNiNzY2NGRkIiwidHlwZSI6IkVkMjU1MTlWZXJpZmljYXRpb25LZXkyMDE4IiwiY29udHJvbGxlciI6IiNpZCIsInB1YmxpY0tleUJhc2U1OCI6IkV6VnZHSm1mWTZXaUdlYWZmbzJMWlBLVmpvcEFrMlBzNXFncVJhQ1Vyd2gxIn1dLCJrZXlBZ3JlZW1lbnQiOlt7ImlkIjoiIzUwNDQxZWM0LTcyZWItNDIzOC05ODM1LTEzZjg0NTI5M2M2NSIsInR5cGUiOiJYMjU1MTlLZXlBZ3JlZW1lbnRLZXkyMDE5IiwiY29udHJvbGxlciI6IiNpZCIsInB1YmxpY0tleUJhc2U1OCI6IjlBM3BhdlZETkFoN0NwajJuYUdBVmY1eGlNazV2WUxwUVZuRkZqRnBZYjJDIn1dfQ==",
      "jws": {
        "protected": "eyJhbGciOiJFZERTQSIsImp3ayI6eyJrdHkiOiJPS1AiLCJjcnYiOiJFZDI1NTE5IiwieCI6InotSzc5czVQZVlOd3ZzODE2VzU4VjRyc1NpWi1XU0tYdmNnX1ozNlM3eUEifX0",
        "signature": "N-_ig4v3S-4Jt8iKy6eWkg-wocqjY5FC91WtgunFzoO8ZVjmxkYBGu9tr9hk4-lYao0I_2OfxvLnWk50zEfhCQ",
        "header": {
          "kid": "did:key:z6MktSkxrZ26se1BP9RNMMzBQUsVZP629ueDmrbmFrAVnAUP"
        }
      }
    }
  }
}
```

Decoded attachment:
```json
{
  "@context": [
    "https://w3id.org/did/v1"
  ],
  "id": "did:peer:1zQmd5sQ7mhYcbwtr5L6fQ1KfwFYtEGU3mCpedeBtgmycXC5",
  "service": [
    {
      "id": "#inline-0",
      "serviceEndpoint": "didcomm:transport/queue",
      "type": "did-communication",
      "priority": 0,
      "recipientKeys": [
        "#73d06a3b-74d5-4f9a-b8c7-e075cb7664dd"
      ],
      "routingKeys": []
    }
  ],
  "authentication": [
    {
      "id": "#73d06a3b-74d5-4f9a-b8c7-e075cb7664dd",
      "type": "Ed25519VerificationKey2018",
      "controller": "#id",
      "publicKeyBase58": "EzVvGJmfY6WiGeaffo2LZPKVjopAk2Ps5qgqRaCUrwh1"
    }
  ],
  "keyAgreement": [
    {
      "id": "#50441ec4-72eb-4238-9835-13f845293c65",
      "type": "X25519KeyAgreementKey2019",
      "controller": "#id",
      "publicKeyBase58": "9A3pavVDNAh7Cpj2naGAVf5xiMk5vYLpQVnFFjFpYb2C"
    }
  ]
}
```

Decoded protected headers:
```json
{
  "alg": "EdDSA",
  "jwk": {
    "kty": "OKP",
    "crv": "Ed25519",
    "x": "z-K79s5PeYNwvs816W58V4rsSiZ-WSKXvcg_Z36S7yA"
  }
}
```

Error on ACA-Py:
```python
2023-11-17 02:07:55,576 aries_cloudagent.core.dispatcher ERROR Handler error: Dispatcher.handle_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/aries_cloudagent/core/dispatcher.py", line 253, in handle_message
    await handler(context, responder)
  File "/aries_cloudagent/protocols/didexchange/v1_0/handlers/request_handler.py", line 39, in handle
    conn_rec = await mgr.receive_request(
  File "/aries_cloudagent/protocols/didexchange/v1_0/manager.py", line 486, in receive_request
    conn_did_doc = await self.verify_diddoc(wallet, request.did_doc_attach)
  File "/aries_cloudagent/protocols/didexchange/v1_0/manager.py", line 940, in verify_diddoc
    if not await attached.data.verify(wallet, invi_key):
  File "/aries_cloudagent/messaging/decorators/attach_decorator.py", line 452, in verify
    encoded_pk = DIDKey.from_did(protected["jwk"]["kid"]).public_key_b58
KeyError: 'kid'
```

### PR DESCRIPTION
**Pull request by dbluhm**
Fixes #2608.

This PR makes the signed attachment verification a bit more resilient. According to [RFC 7515](https://datatracker.ietf.org/doc/html/rfc7515), there's no reason for us to strictly expect a `kid` to be present in the `jwk` and we can verify that the jwk corresponds to the kid in the header trivially. In short, the previous rigidity was unnecessary. This corrects that.

### CODE REVIEW

**Comment by dbluhm** [comment]
@swcurran acknowledging that we're somewhere on the verge of 0.11.0, I have no preference for whether this ends up in this release or a follow up patch release (I'll have other bigger changes queued up for a patch for things like did:peer:2 anyways).

**Comment by usingtechnology** [comment]
@dbluhm - in Thailand so will not be able to review. Back late November.

**Comment by swcurran** [comment]
@andrewwhitehead — since @usingtechnology is not around, can you please take a look at this one?  Looks pretty straight forward to me :-)

**Comment by swcurran** [comment]
Looks like the only change is to add a check for the `kid` before using it, instead of just using it. Right?

**Comment by dbluhm** [comment]
@swcurran pretty much, yep

**Review by swcurran — APPROVED** [review]

**Pull request merged**
