### PR TITLE
Enable Snyk scanning

### PR DESCRIPTION
**Pull request by ryjones**
addresses #2087

### CODE REVIEW

**Comment by swcurran** [comment]
Ouch…236 open issues.  That’s painful.

The three “high” issues are the same thing and are likely fine.  We’ll need guidance on how to mark “uninteresting” issues — presumably that is the docs.

Thanks for doing this, @ryjones — awesome stuff.

Aside — I had to edit the “github-code-scanning” comment, as the link to the overview was bad — unusable in email.  Anything we need to do about that?

**Comment by dbluhm** [comment]
Several of the low severity ones would be taken care of by #2310, I think

**Comment by ryjones** [comment]
@swcurran I think the reason it didn't work was it didn't exist yet

**Comment by swcurran** [comment]
> @swcurran I think the reason it didn't work was it didn't exist yet

I don’t think so.  When I fixed the link, I could navigate to the content, so it existed. The link started with “hyperledger/aries-cloudagent-python…” — it didn’t have github.com in the URL. Might have been related to the link going into an email.  Anyway, we can deal with that later.

**Comment by ryjones** [comment]
@swcurran sounds good. Please approve and merge

**Review by dbluhm — APPROVED** [review]

**Pull request merged**
