### PR TITLE
Add .indy_client folder to Askar only image.

### PR DESCRIPTION
**Pull request by WadeBarnes**
Fixes https://github.com/hyperledger/aries-cloudagent-python/issues/2307

### CODE REVIEW

**Comment by swcurran** [comment]
@loneil — are you able to test with this updated Dockerfile?

**Comment by loneil** [comment]
> @loneil — are you able to test with this updated Dockerfile?

My docker-ing is relatively weak in this area, but since we're basing on the published image 
`FROM ghcr.io/hyperledger/aries-cloudagent-python:py3.9-0.8.2 as base`
can I import based on the change to the dockerfile in this branch/fork? Or do I need a new published/tag image?

**Comment by WadeBarnes** [comment]
Once the changes are merged I can build and publish a new image (without having to do a release) for testing you could reference.

**Review by swcurran — APPROVED** [review]

**Comment by loneil** [comment]
@swcurran @WadeBarnes thanks for publishing image!
Trying with `ghcr.io/hyperledger/aries-cloudagent-python:py3.9-0.8.3-pre` on an OpenShift deployment I am now able to create and issue and revoke revocable credentials.
The `.indy_client` folder is in the pod with tails files with appropriate permissions now.

**Pull request merged**
