### PR TITLE
Changelog, version and ReadTheDocs updates for 0.7.4-rc3 release

### PR DESCRIPTION
**Pull request by swcurran**
Signed-off-by: Stephen Curran <swcurran@gmail.com>

### CODE REVIEW

**Comment by swcurran** [comment]
@andrewwhitehead @shaangill025 -- please review/approve and I'll tag the release.

**Comment by andrewwhitehead** [comment]
There's a bunch of issues that were essentially WONTFIX or we could never diagnose the problem, or were fixed in previous releases. I identified these ones but haven't looked at newer issue numbers:

1037
1239
1309
1310
1319
1444
1462
1499
1505
1513
1520
1546
1547
1555
1559
1568
1582
1598
1625
1634
1644
1664

**Comment by swcurran** [comment]
Ah...shoot -- I didn't intend to include that file.  I'll remove it.

**Comment by swcurran** [comment]
OK - corrected.  Sorry about that.

**Review by andrewwhitehead — APPROVED** [review]

**Pull request merged**
