### PR TITLE
chore: point to official sd-jwt lib release

### PR DESCRIPTION
**Pull request by dbluhm**
This PR adjusts the version of sd-jwt pulled to be the official release now published to PyPI: https://pypi.org/project/sd-jwt/

### CODE REVIEW

**Comment by dbluhm** [comment]
@swcurran I think it would be good to get this in for 0.11.0; assuming tests pass, I think it's a pretty innocuous change and removes the only "unofficial"/git dependency we have, which should make integrating with ACA-Py from plugins or elsewhere simpler.

**Comment by swcurran** [comment]
Before or after 0.11.0-rc0?  Does it matter?

**Comment by dbluhm** [comment]
Either way works for me!

**Review by swcurran — APPROVED** [review]
LGTM.  Should have merged before 0.11.0-rc0, as it failed to publish, likely because of this.  :-(

**Pull request merged**
