### PR TITLE
Allow custom message prefixes; simplify message type registration

### PR DESCRIPTION
**Pull request by andrewwhitehead**

### CODE REVIEW

**Review by sklump — APPROVED** [review]

**Review by ianco — CHANGES_REQUESTED** [review]
I built a local aca-py image and tried starting up aries-vcr and I get the following:

vcr-agent_1    | 2020-10-06 22:40:38,387 aries_cloudagent.core.conductor ERROR Exception in message handler:
vcr-agent_1    | Traceback (most recent call last):
vcr-agent_1    |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/core/dispatcher.py", line 139, in handle_message
vcr-agent_1    |     message = await self.make_message(inbound_message.payload)
vcr-agent_1    |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/core/dispatcher.py", line 223, in make_message
vcr-agent_1    |     instance = message_cls.deserialize(parsed_msg)
vcr-agent_1    | AttributeError: 'tuple' object has no attribute 'deserialize'
vcr-agent_1    | 2020-10-06 22:40:38,388 aries_cloudagent.core.conductor ERROR DON'T shutdown on AttributeError 'tuple' object has no attribute 'deserialize'
vcr-agent_1    | 2020-10-06 22:40:38,389 aries_cloudagent.core.dispatcher ERROR Handler error: Dispatcher.handle_message
vcr-agent_1    | Traceback (most recent call last):
vcr-agent_1    |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/core/dispatcher.py", line 139, in handle_message
vcr-agent_1    |     message = await self.make_message(inbound_message.payload)
vcr-agent_1    |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/core/dispatcher.py", line 223, in make_message
vcr-agent_1    |     instance = message_cls.deserialize(parsed_msg)
vcr-agent_1    | AttributeError: 'tuple' object has no attribute 'deserialize'

**Comment by ianco** [comment]
I *think* it's getting a connection error and not interpreting it properly

**Comment by ianco** [comment]
... also breaks the BC Reg issuer registration:

bcreg-controller_1  | Traceback (most recent call last):
bcreg-controller_1  |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
bcreg-controller_1  |     self.run()
bcreg-controller_1  |   File "/home/indy/src/issuer.py", line 325, in run
bcreg-controller_1  |     response.raise_for_status()
bcreg-controller_1  |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
bcreg-controller_1  |     raise HTTPError(http_error_msg, response=self)
bcreg-controller_1  | requests.exceptions.HTTPError: 418 Client Error:  for url: http://bcreg-agent:8034/issuer_registration/send

**Comment by sklump** [comment]
I can't guess what the update has to do with this error. Tuple??

**Comment by ianco** [comment]
> I can't guess what the update has to do with this error. Tuple??

Working back from the stack trace, this line:

https://github.com/andrewwhitehead/aries-cloudagent-python/blob/feat/custom-prefix/aries_cloudagent/core/dispatcher.py#L215

... is returning a tuple:

message_cls: ('aries_cloudagent.protocols.connections.v1_0.messages.connection_request.ConnectionRequest',)

... and the exception is getting thrown when you try to call deserialize()

**Comment by andrewwhitehead** [comment]
@ianco Should be fixed now

**Review by ianco — APPROVED** [review]
Tested, all working now

**Review by sklump — APPROVED** [review]

**Pull request merged**
