### PR TITLE
Changing acme initialization to be like Alice and Faber ones

### PR DESCRIPTION
**Pull request by afrancoc2000**
Signed-off-by: Ana Maria Franco Cuesta <afrancoc2000@gmail.com>
Fixing the issue [here](https://github.com/hyperledger/aries-cloudagent-python/issues/1288)

### CODE REVIEW

**Comment by swcurran** [comment]
@ianco -- one for you to review, please.

**Review by ianco — CHANGES_REQUESTED** [review]
Looks good!  These is just a small problem with formatting.

You can run:

```
pip install black
black demo/runners
```

... and it will fix up the formatting, and then you can check in the update and all tests should pass.

Thanks for the contribution!

**Comment by afrancoc2000** [comment]
Hi @ianco, I changed the formatting as you said and changed the code in the demo also so they are in sync.
Thank you!

**Comment by ianco** [comment]
Hi @afrancoc2000 thanks for the update!  Unfortunately there is now a conflict due to some documentation changes made late this week, can you please fix the conflict?  And then we can merge your PR.

Thanks again for the contribution!

**Comment by afrancoc2000** [comment]
Hi @ianco, I fixed the conflict, please tell me if there's anything else I need to do. Thanks!

**Review by ianco — APPROVED** [review]

**Pull request merged**
