### PR TITLE
query strings are always strings

### PR DESCRIPTION
**Pull request by sklump**
Signed-off-by: sklump <srklump@hotmail.com>

### CODE REVIEW

**Comment by sklump** [comment]
Can anyone tell me what this bullshit is? I am not creating another account.

**Comment by swcurran** [comment]
test_sign_credential - aries_cloudagent.messaging.jsonld.tests.test_routes.TestJSONLDRoutes
aries_cloudagent/messaging/jsonld/tests/test_routes.py
self = <aries_cloudagent.messaging.jsonld.tests.test_routes.TestJSONLDRoutes testMethod=test_sign_credential>

```
    async def test_sign_credential(self):
        mock_request = async_mock.MagicMock(
            app=self.app,
            json=async_mock.CoroutineMock(
                return_value={  # posted json
                    "verkey": self.did_info.verkey,
                    "doc": {
                        "credential": {
                            "@context": [
                                "https://www.w3.org/2018/credentials/v1",
                                "https://www.w3.org/2018/credentials/examples/v1",
                            ],
                            "id": "http://example.gov/credentials/3732",
                            "type": [
                                "VerifiableCredential",
                                "UniversityDegreeCredential",
                            ],
                            "issuer": (
                                "did:key:"
                                "z6MkjRagNiMu91DduvCvgEsqLZDVzrJzFrwahc4tXLt9DoHd"
                            ),
                            "issuanceDate": "2020-03-10T04:24:12.164Z",
                            "credentialSubject": {
                                "id": (
                                    "did:key:"
                                    "z6MkjRagNiMu91DduvCvgEsqLZDVzrJzFrwahc4tXLt9DoHd"
                                ),
                                "degree": {
                                    "type": "BachelorDegree",
                                    "name": u"Bachelor of Encyclopædic Arts",
                                },
                            },
                        },
                        "options": {
                            "type": "Ed25519Signature2018",
                            "created": "2020-04-10T21:35:35Z",
                            "verificationMethod": (
                                "did:key:"
                                "z6MkjRagNiMu91DduvCvgEsqLZDVzrJzFrwahc4tXLt9DoHd#"
                                "z6MkjRagNiMu91DduvCvgEsqLZDVzrJzFrwahc4tXLt9DoHd"
                            ),
                            "proofPurpose": "assertionMethod",
                        },
                    },
                }
            ),
        )
 ```
   
        with async_mock.patch.object(test_module.web, "json_response") as mock_response:
            result = await test_module.sign(mock_request)
            assert result == mock_response.return_value
            mock_response.assert_called_once()
>           assert "signed_doc" in mock_response.call_args[0][0]
E           AssertionError: assert 'signed_doc' in {'error': '(\'Could not process context before compaction.\',)\nType: jsonld.CompactError\nCause: (\'Dereferencing a U...6/site-packages/pyld/context_resolver.py", line 157, in _fetch_context\n    code=\'loading remote context failed\')\n'}

aries_cloudagent/messaging/jsonld/tests/test_routes.py:135: AssertionError
test_verify_credential - aries_cloudagent.messaging.jsonld.tests.test_routes.TestJSONLDRoutes
aries_cloudagent/messaging/jsonld/tests/test_routes.py
AssertionError: Expected call: json_response({'valid': True}) Actual call: json_response({'valid': False, 'error': '(\'Could not convert input to RDF dataset before normalization.\',)\nType: jsonld.NormalizeError\nCause: (\'Could not expand input before serialization to RDF.\',)\nType: jsonld.RdfError\nCause: (\'Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.\',)\nType: jsonld.InvalidUrl\nCode: loading remote context failed\nDetails: {\'url\': \'https://w3id.org/security/v1\', \'cause\': JsonLdError(\'Could not retrieve a JSON-LD document from the URL.\',)}  File "/home/indy/.local/lib/python3.6/site-packages/pyld/jsonld.py", line 1219, in to_rdf\n    expanded = self.expand(input_, options)\n  File "/home/indy/.local/lib/python3.6/site-packages/pyld/jsonld.py", line 871, in expand\n    inside_list=False)\n  File "/home/indy/.local/lib/python3.6/site-packages/pyld/jsonld.py", line 2303, in _expand\n    active_ctx, element[\'@context\'], options)\n  File "/home/indy/.local/lib/python3.6/site-packages/pyld/jsonld.py", line 3049, in _process_context\n    resolved = options[\'contextResolver\'].resolve(active_ctx, local_ctx, options.get(\'base\', \'\'))\n  File "/home/indy/.local/lib/python3.6/site-packages/pyld/context_resolver.py", line 59, in resolve\n    active_ctx, ctx, base, cycles)\n  File "/home/indy/.local/lib/python3.6/site-packages/pyld/context_resolver.py", line 115, in _resolve_remote_context\n    resolved = self.resolve(active_ctx, context, base, cycles)\n  File "/home/indy/.local/lib/python3.6/site-packages/pyld/context_resolver.py", line 59, in resolve\n    active_ctx, ctx, base, cycles)\n  File "/home/indy/.local/lib/python3.6/site-packages/pyld/context_resolver.py", line 108, in _resolve_remote_context\n    context, remote_doc = self._fetch_context(active_ctx, url, cycles)\n  File "/home/indy/.local/lib/python3.6/site-packages/pyld/context_resolver.py", line 157, in _fetch_context\n    code=\'loading remote context failed\')\n  File "/home/indy/.local/lib/python3.6/site-packages/pyld/jsonld.py", line 1128, in normalize\n    dataset = self.to_rdf(input_, opts)\n  File "/home/indy/.local/lib/python3.6/site-packages/pyld/jsonld.py", line 1223, in to_rdf\n    \'RDF.\', \'jsonld.RdfError\', cause=cause)\n'})
self = <aries_cloudagent.messaging.jsonld.tests.test_routes.TestJSONLDRoutes testMethod=test_verify_credential>

```
    async def test_verify_credential(self):
        mock_request = async_mock.MagicMock(
            app=self.app,
            json=async_mock.CoroutineMock(
                return_value={  # posted json
                    "verkey": (
                        # pulled from the did:key in example
                        "5yKdnU7ToTjAoRNDzfuzVTfWBH38qyhE1b9xh4v8JaWF"
                    ),
                    "doc": {
                        "@context": [
                            "https://www.w3.org/2018/credentials/v1",
                            "https://www.w3.org/2018/credentials/examples/v1",
                        ],
                        "id": "http://example.gov/credentials/3732",
                        "type": ["VerifiableCredential", "UniversityDegreeCredential"],
                        "issuer": (
                            "did:key:z6MkjRagNiMu91DduvCvgEsqLZDVzrJzFrwahc4tXLt9DoHd"
                        ),
                        "issuanceDate": "2020-03-10T04:24:12.164Z",
                        "credentialSubject": {
                            "id": (
                                "did:key:"
                                "z6MkjRagNiMu91DduvCvgEsqLZDVzrJzFrwahc4tXLt9DoHd"
                            ),
                            "degree": {
                                "type": "BachelorDegree",
                                "name": "Bachelor of Science and Arts",
                            },
                        },
                        "proof": {
                            "type": "Ed25519Signature2018",
                            "created": "2020-04-10T21:35:35Z",
                            "verificationMethod": (
                                "did:key:"
                                "z6MkjRagNiMu91DduvCvgEsqLZDVzrJzFrwahc"
                                "4tXLt9DoHd#z6MkjRagNiMu91DduvCvgEsqLZD"
                                "VzrJzFrwahc4tXLt9DoHd"
                            ),
                            "proofPurpose": "assertionMethod",
                            "jws": (
                                "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaX"
                                "QiOlsiYjY0Il19..l9d0YHjcFAH2H4dB9xlWFZQLUp"
                                "ixVCWJk0eOt4CXQe1NXKWZwmhmn9OQp6YxX0a2Lffe"
                                "gtYESTCJEoGVXLqWAA"
                            ),
                        },
                    },
                }
            ),
        )
```
    
        with async_mock.patch.object(test_module.web, "json_response") as mock_response:
            result = await test_module.verify(mock_request)
            assert result == mock_response.return_value
>           mock_response.assert_called_once_with({"valid": True})  # expected response

aries_cloudagent/messaging/jsonld/tests/test_routes.py:81: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../.pyenv/versions/3.6.9/lib/python3.6/unittest/mock.py:825: in assert_called_once_with
    return self.assert_called_with(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

_mock_self = <MagicMock name='json_response' id='139942374032720'>
args = ({'valid': True},), kwargs = {}, expected = (({'valid': True},), {})
_error_message = <function NonCallableMock.assert_called_with.<locals>._error_message at 0x7f46de4bc8c8>
actual = call({'valid': False, 'error': '(\'Could not convert input to RDF dataset before normalization.\',)\nType: jsonld.Norm...lib/python3.6/site-packages/pyld/jsonld.py", line 1223, in to_rdf\n    \'RDF.\', \'jsonld.RdfError\', cause=cause)\n'})
cause = None

    def assert_called_with(_mock_self, *args, **kwargs):
        """assert that the mock was called with the specified arguments.
    
        Raises an AssertionError if the args and keyword args passed in are
        different to the last call to the mock."""
        self = _mock_self
        if self.call_args is None:
            expected = self._format_mock_call_signature(args, kwargs)
            raise AssertionError('Expected call: %s\nNot called' % (expected,))
    
        def _error_message():
            msg = self._format_mock_failure_message(args, kwargs)
            return msg
        expected = self._call_matcher((args, kwargs))
        actual = self._call_matcher(self.call_args)
        if expected != actual:
            cause = expected if isinstance(expected, Exception) else None
>           raise AssertionError(_error_message()) from cause
E           AssertionError: Expected call: json_response({'valid': True})
E           Actual call: json_response({'valid': False, 'error': '(\'Could not convert input to RDF dataset before normalization.\',)\nType: jsonld.NormalizeError\nCause: (\'Could not expand input before serialization to RDF.\',)\nType: jsonld.RdfError\nCause: (\'Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.\',)\nType: jsonld.InvalidUrl\nCode: loading remote context failed\nDetails: {\'url\': \'https://w3id.org/security/v1\', \'cause\': JsonLdError(\'Could not retrieve a JSON-LD document from the URL.\',)}  File "/home/indy/.local/lib/python3.6/site-packages/pyld/jsonld.py", line 1219, in to_rdf\n    expanded = self.expand(input_, options)\n  File "/home/indy/.local/lib/python3.6/site-packages/pyld/jsonld.py", line 871, in expand\n    inside_list=False)\n  File "/home/indy/.local/lib/python3.6/site-packages/pyld/jsonld.py", line 2303, in _expand\n    active_ctx, element[\'@context\'], options)\n  File "/home/indy/.local/lib/python3.6/site-packages/pyld/jsonld.py", line 3049, in _process_context\n    resolved = options[\'contextResolver\'].resolve(active_ctx, local_ctx, options.get(\'base\', \'\'))\n  File "/home/indy/.local/lib/python3.6/site-packages/pyld/context_resolver.py", line 59, in resolve\n    active_ctx, ctx, base, cycles)\n  File "/home/indy/.local/lib/python3.6/site-packages/pyld/context_resolver.py", line 115, in _resolve_remote_context\n    resolved = self.resolve(active_ctx, context, base, cycles)\n  File "/home/indy/.local/lib/python3.6/site-packages/pyld/context_resolver.py", line 59, in resolve\n    active_ctx, ctx, base, cycles)\n  File "/home/indy/.local/lib/python3.6/site-packages/pyld/context_resolver.py", line 108, in _resolve_remote_context\n    context, remote_doc = self._fetch_context(active_ctx, url, cycles)\n  File "/home/indy/.local/lib/python3.6/site-packages/pyld/context_resolver.py", line 157, in _fetch_context\n    code=\'loading remote context failed\')\n  File "/home/indy/.local/lib/python3.6/site-packages/pyld/jsonld.py", line 1128, in normalize\n    dataset = self.to_rdf(input_, opts)\n  File "/home/indy/.local/lib/python3.6/site-packages/pyld/jsonld.py", line 1223, in to_rdf\n    \'RDF.\', \'jsonld.RdfError\', cause=cause)\n'})

../.pyenv/versions/3.6.9/lib/python3.6/unittest/mock.py:814: AssertionError

**Comment by sklump** [comment]
I didn't touch any of this code. Something's busted.

**Comment by sklump** [comment]
Oh! I bet it's a timeout. Remember this hosebeast of a package takes about 20-30 seconds do to anything real.

**Review by andrewwhitehead — APPROVED** [review]

**Review by andrewwhitehead — APPROVED** [review]

**Pull request merged**
