### PR TITLE
Relax validation of holder DID when submitting a credential request

### PR DESCRIPTION
**Pull request by ianco**
See issue https://github.com/hyperledger/aries-cloudagent-python/issues/2714

Relax validation to allow did:peer (or any value) for the holder/prover did on a credential request.

This works with an askar wallet, but anoncreds-askar will fail due to its own did validation (see issue https://github.com/hyperledger/anoncreds-rs/issues/307)

This PR will work once the anoncreds-rs issue is also fixed.

### CODE REVIEW

**Comment by swcurran** [comment]
The AnonCreds issue has been resolved and the PR is part of the 0.2.0-dev8 that was published tonight. I'll add a ticket to update ACA-Py to use that release. Since @jamshale did the 0.2.0-dev7 update, I'll ask if he can do the 0.2.0-dev8 one as well.

**Review by jamshale — DISMISSED** [review]

**Comment by ianco** [comment]
Hmmm integration tests are failing I'll take a look ...

**Comment by jamshale** [comment]
> Hmmm integration tests are failing I'll take a look ...

Those were different than the ones failing for me locally. Might be the sporadic fail that happens sometimes :man_shrugging:

**Comment by ianco** [comment]
> > Hmmm integration tests are failing I'll take a look ...
> 
> Those were different than the ones failing for me locally. Might be the sporadic fail that happens sometimes 🤷‍♂️

Could be I'm trying to run locally

**Comment by ianco** [comment]
> > Hmmm integration tests are failing I'll take a look ...
> 
> Those were different than the ones failing for me locally. Might be the sporadic fail that happens sometimes 🤷‍♂️

This error:

```
anoncreds.error.AnoncredsError: type: RevocationRegistryDefinitionId, identifier: 5VieLs9kRQ2gMXWoxbKewg:4:5VieLs9kRQ2gMXWoxbKewg:3:CL:53:Acme.agent.Schema_DriversLicense_v2:CL_ACCUM:1 is invalid. It MUST be a URI or legacy identifier.
```

Investigating ...

**Comment by ianco** [comment]
The alice/faber demo is working but the integration tests are failing ...  grrrr ...

**Comment by ianco** [comment]
@jamshale  just double checked and the same integration tests were failing on your PR (which we merged).  There was *also* one of our famous random failures ...

I think the anoncreds-rs update affected the validation for the revocation registry id, I'll log another issue on the anoncreds-rs repo.

**Review by jamshale — APPROVED** [review]

**Pull request merged**
