### PR TITLE
[ PATCH ] 0.12.x with PR 3081 terse webhooks

### PR DESCRIPTION
**Pull request by jamshale**
Cherry picks https://github.com/hyperledger/aries-cloudagent-python/pull/3081 commits for the 0.12.x patch release.

Need to run integration tests locally. There was no merge conflicts.

### CODE REVIEW

**Comment by jamshale** [comment]
I don't understand why snyk is complaining about some sort of merge conflict?

**Comment by jamshale** [comment]
Passed all the `GHA` integration tests locally.

**Comment by swcurran** [comment]
Any ideas on the the Snyk failure?

Do we need an 0.12.2rc2 or just include this and declare it final?

**Review by esune — APPROVED** [review]
Changes look good to me. I can't (yet) access the Snyk report so I am unable to help with that.

**Comment by jamshale** [comment]
I think the snyk scan just has issues with dockerfiles scanned for main and then re-scanned on a lts branch and says there's a merge conflict because the bas image is different. I marked it as passed.

**Pull request merged**
