### PR TITLE
fix Openapi validation

### PR DESCRIPTION
**Pull request by mat-work**
Open API specification does not currently validate correctly and causes openapi generator to crash or produce invalid code.

A PR was created to fix related issues with aiohttp-apispec: https://github.com/maximdanilchenko/aiohttp-apispec/pull/104

### CODE REVIEW

**Comment by sklump** [comment]
Use `messaging.models.openapi.OpenAPISchema` as base class, not raw `Schema`, for all `@request_schema`, `@response_schema`, `@match_info_schema`, `@querystring_schema`. For `admin/server.py` too, this is a good time to fix those: I'd missed them.

**Comment by ianco** [comment]
FYI there are a couple of flake8 tests failing:

FLAKE8 - aries_cloudagent.revocation.routes
aries_cloudagent/revocation/routes.py
/home/indy/project/aries_cloudagent/revocation/routes.py:16:1: F401 'marshmallow.Schema' imported but unused
FLAKE8 - aries_cloudagent.wallet.routes
aries_cloudagent/wallet/routes.py
/home/indy/project/aries_cloudagent/wallet/routes.py:12:1: F401 'marshmallow.Schema' imported but unused

**Comment by mat-work** [comment]
> FYI there are a couple of flake8 tests failing:
> 
> FLAKE8 - aries_cloudagent.revocation.routes
> aries_cloudagent/revocation/routes.py
> /home/indy/project/aries_cloudagent/revocation/routes.py:16:1: F401 'marshmallow.Schema' imported but unused
> FLAKE8 - aries_cloudagent.wallet.routes
> aries_cloudagent/wallet/routes.py
> /home/indy/project/aries_cloudagent/wallet/routes.py:12:1: F401 'marshmallow.Schema' imported but unused

thanks, it should be fine now.

**Review by ianco — APPROVED** [review]

**Review by sklump — APPROVED** [review]

**Comment by ianco** [comment]
@mat-work  you'll need to merge the latest changes from master into your PR before we can merge it

**Comment by mat-work** [comment]
> @mat-work you'll need to merge the latest changes from master into your PR before we can merge it

done. many thanks.

**Pull request merged**
