### PR TITLE
Fix multitenant/mediation in demo

### PR DESCRIPTION
**Pull request by ianco**
Signed-off-by: Ian Costanzo <ian@anon-solutions.ca>

Tweaked the mediation code in the alice/faber demo (wasn't working properly).

Working with the fix from @usingtechnology  in PR # 2232

### CODE REVIEW

**Comment by dbluhm** [comment]
This is code I've touched recently. I'll try to squeeze in some time to take a look!

**Review by usingtechnology — DISMISSED** [review]
Looks good to me.

**Comment by swcurran** [comment]
Re-running the failed tests...

**Comment by swcurran** [comment]
Tests still failing.  @usingtechnology — could you please take a look?

**Comment by ianco** [comment]
Weird situation because Flake8 is failing in one of the libraries, not aca-py code :-(

**Comment by ianco** [comment]
> Tests still failing. @usingtechnology — could you please take a look?

I took out a couple of code changes I made which don't seem to be doing anything and I don't recall why I made :-S

**Review by dbluhm — APPROVED** [review]

**Pull request merged**
