### PR TITLE
Support (Aries RFC 36) issue-credential protocol v1.1

### PR DESCRIPTION
**Pull request by sklump**
Address https://github.com/hyperledger/aries-cloudagent-python/issues/341

Signed-off-by: sklump <srklump@hotmail.com>

### CODE REVIEW

**Comment by swcurran** [comment]
It turns out that the v1.1 upgrade was inappropriately handled for this. The version is on the protocol, not on the messages, so what should have happened (and what will be corrected) is that ALL of the messages will have the v1.1 tag on them.

A further complication is that the change that was made to go from v1.0 was to add Indy specific data to the proposal message.  However, we took pains to prevent Indy specific data in the other credential exchange messages -- through the use of attachments.  We need to relook at the change in that light.

More discussion in the community...

**Comment by sklump** [comment]
What is indy-specific in the proposal message?

**Comment by swcurran** [comment]
That's good about the message types. The RFC needs to be updated.

The Indy-specific fields are these ones:

-    "schema_issuer_did": "DID of the proposed schema issuer",
-    "schema_id": "Schema ID string",
-    "schema_name": "Schema name string",
-    "schema_version": "Schema version string",
-    "cred_def_id": "Credential Definition ID string"

**Comment by sklump** [comment]
I guess the way forward here would be to base64-encode and wrap the five-or-six* criteria into a "filter~attach" attachment.

*  in or out: issuer_did.
IN:
+ one place for all filter criteria
- not backward-compatible with v1.0
OUT:
+ backward-compatible with v1.0
- need to visit two places to assemble filtration criteria: we're only on v1.1 and it's already got a tumour
An a

**Pull request closed without merging**
