### PR TITLE
Remove Indy tests from workflows

### PR DESCRIPTION
**Pull request by dbluhm**
As discussed recently and captured in #2402, this PR removes Indy specific tests from PR test runs. This also adjusts other images and examples in the demo folder to use the non-indy variant of images.

### CODE REVIEW

**Review by swcurran — DISMISSED** [review]
LGTM — ran the Alice-Faber demo and everything worked as normal.

**Comment by swcurran** [comment]
The indy tests are being removed, so need not pass, right? Go ahead and merge?  Do we put this in 0.10.0?  I think so...

**Comment by WadeBarnes** [comment]
I can adjust the branch protection rules once the PR is merged.

I'd say remove the nightly test workflow for now.  We can always reinstate things later if the needs arise.

Should this PR include removal of the indy-sdk related build/publish workflows, or is that going to be a separate PR?

**Comment by swcurran** [comment]
I’d say separate PR for the indy/sdk removal for publishing. Hold off on that for a bit.

**Comment by dbluhm** [comment]
K, I will go ahead and remove the nightly workflows.

**Comment by dbluhm** [comment]
This is ready to merge whenever we're ready to pull the trigger on this change @swcurran @WadeBarnes

**Review by swcurran — APPROVED** [review]

**Comment by swcurran** [comment]
Updated the branch protection rules to remove the Indy Test.

**Pull request merged**
