### PR TITLE
0.12.1

### PR DESCRIPTION
**Pull request by swcurran**
Signed-off-by: Stephen Curran <swcurran@gmail.com>

### CODE REVIEW

**Comment by swcurran** [comment]
@jamshale -- could you please look at the integration test error? Presumably intermittent, but not one I recognize.

**Review by dbluhm — APPROVED** [review]
Testing with example scenarios in minimal example repo all look good: https://github.com/Indicio-tech/acapy-minimal-example/pull/88

Tests against Credo (run locally) also passed using the 0.12.1rc1 image.

LGTM! Assuming the integration test failure is indeed just an intermittent issue.

**Comment by jamshale** [comment]
The integration test got a duplicate record error setting up endorser roles. I've never seen this before. I'd like to have a look at this closer and figure out if it's a blocking issue or not.

**Comment by jamshale** [comment]
I'm going to look into that error from the integration tests and make a ticket. I'm sure it's intermittent and already existed, but still, it shouldn't be able to happen. 

Doesn't affect the release.

**Comment by jamshale** [comment]
FYI on the failed integration test. Seems like, somehow the test created a race condition, by duplicating a /set-endorser-role request, with these lines.
```
7hAcme.agent | Updating endorser role for connection: d6283a4d-aa71-49b7-9e80-aa58f69cd8f7, TRANSACTION_ENDORSER
7hAcme.agent | Updating endorser role for connection: d6283a4d-aa71-49b7-9e80-aa58f69cd8f7, TRANSACTION_ENDORSER
```
creating a duplicate record. I tried to recreate the problem but haven't been able to. Because I've never seen this error before and seems very unlikely to happen on this endpoint in practice, I'd say we don't have to worry about it.

**Pull request merged**
