### PR TITLE
Rfc592 453 454

### PR DESCRIPTION
**Pull request by sklump**
Implements https://github.com/hyperledger/aries-rfcs/pull/607

### CODE REVIEW

**Comment by sklump** [comment]
More changes to come, pending resolution of https://github.com/hyperledger/aries-rfcs/pull/607

**Comment by sklump** [comment]
OK, good to go IMO

**Comment by sklump** [comment]
I just want to revisit and expand bait-and-switch before I call this done - early this afternoon

**Comment by sklump** [comment]
OK, good now

**Review by TimoGlastra — APPROVED** [review]
LGTM. Seems like this won't be too much of a hassle to merge with our code!

**Review by andrewwhitehead — APPROVED** [review]

**Review by ianco — APPROVED** [review]

**Pull request merged**
