### PR TITLE
#2041 - Issue JSON-LD has invalid Admin API documentation

### PR DESCRIPTION
**Pull request by jfblier-amplitude**
cc @swcurran @ianco 

The demo AliceWantsAJsonCredential.md has invalid Admin API endpoints documented.

Signed-off-by: Jean-Francois Blier <101359928+jfblier-amplitude@users.noreply.github.com>

### CODE REVIEW

**Comment by swcurran** [comment]
@ianco -- if you have time, please take a look.

**Comment by ianco** [comment]
The update looks good, a bunch of tests are failing so I'm trying to re-run again

**Review by ianco — APPROVED** [review]

**Comment by ianco** [comment]
Weird the code format check is failing on files that haven't been changed ...

**Comment by swcurran** [comment]
Andrew mentioned it on the call today.  We need a PR to fix that one line, so that it won't be an issue there after.

**Pull request merged**
