### PR TITLE
1.0.0rc5

### PR DESCRIPTION
**Pull request by swcurran**

### CODE REVIEW

**Comment by swcurran** [comment]
A few tests are failing -- looks like a real issue.  @dbluhm @jamshale -- please take a look and let me know.

**Comment by jamshale** [comment]
@swcurran This is actually looking like a tails server issue from my first observations. Going to try another run.

**Comment by jamshale** [comment]
Hmm... Same thing as last time. I looks like a tails server issue, but maybe not. I'll see if I can figure anything else out and run these tests locally.

**Comment by jamshale** [comment]
These tests are passing locally. Definitely seems like a tails server issue :/

**Comment by jamshale** [comment]
Everything good here now that the tails server got fixed :+1:

**Review by jamshale — APPROVED** [review]

**Pull request merged**
