### PR TITLE
fix: propagate endpoint from mediation record

### PR DESCRIPTION
**Pull request by cjhowland**
This PR solves a bug in #1899 in which the public DID endpoint of an agent behind a mediator was the agent's own endpoint. These changes ensure that a mediated agent's public DID endpoint is the mediator's endpoint.

Signed-off-by: Char Howland <char@indicio.tech>

### CODE REVIEW

**Review by andrewwhitehead — APPROVED** [review]
LGTM

**Comment by swcurran** [comment]
Any insight into the integration test(s) that are failing, @cjhowland ?  Caused by this PR or intermittent?

Thanks

**Comment by andrewwhitehead** [comment]
The integration test failure seems to be intermittent, and could be a bug in the test suite. It's submitting the value 'None' as a revocation registry identifier.

**Comment by andrewwhitehead** [comment]
I think the test failure should be fixed by #1924

**Review by andrewwhitehead — APPROVED** [review]

**Pull request merged**
