### PR TITLE
include image_url in oob invitation

### PR DESCRIPTION
**Pull request by Zzocker**
include `image_url` in out-of-band invitations.

Signed-off-by: Pritam Singh <pkspritam16@gmail.com>

### CODE REVIEW

**Comment by shaangill025** [comment]
Shouldn't `image_url` also be included at https://github.com/hyperledger/aries-cloudagent-python/blob/a7d839a142f99d9ea04afbe41d296f73f4afafec/aries_cloudagent/protocols/out_of_band/v1_0/manager.py#L231?

```
invi_msg = InvitationMessage(  # create invitation message
    _id=invitation_message_id,
    label=my_label or self.profile.settings.get("default_label"),
    handshake_protocols=handshake_protocols,
    requests_attach=message_attachments,
    services=[f"did:sov:{public_did.did}"],
    accept=service_accept if protocol_version != "1.0" else None,
    version=protocol_version or DEFAULT_VERSION,
)
```

**Comment by Zzocker** [comment]
@shaangill025 oh, I missed out when `use_public_did=true`, amended the commit, and forced pushed it.

**Comment by shaangill025** [comment]
@Zzocker You are missing a trailing `,` [should be `image_url=image_url,`] at https://github.com/hyperledger/aries-cloudagent-python/blob/075a2d184ad0575fcbe514094fdbecbb04e24a97/aries_cloudagent/protocols/out_of_band/v1_0/manager.py#L239

You can run `python -m black ./aries_cloudagent` inside aries-cloudagent-python directory to check and fix formatting issues.

**Review by shaangill025 — APPROVED** [review]

**Comment by swcurran** [comment]
Can you please update the this PR?

**Comment by swcurran** [comment]
Apologies -- I didn't get this merged before another came through. I'm not sure why I can't update the base branch, but if you could do that, I'll get this merged.  Thanks!

**Pull request merged**
