### PR TITLE
1.0.0rc6

### PR DESCRIPTION
**Pull request by swcurran**
Signed-off-by: Stephen Curran <swcurran@gmail.com>

### CODE REVIEW

**Comment by swcurran** [comment]
Updated the Changelog to include the 11.1, 11.2, 11.3 and 12.2 entries that weren't released from the `main` branch. Otherwise, a straight forward (I hope) release candidate.

**Review by jamshale — APPROVED** [review]

**Review by dbluhm — APPROVED** [review]

**Review by esune — APPROVED** [review]

**Comment by swcurran** [comment]
Integration tests are failing. I thought it might have been because of the BCovrin reboot this morning, but that was not it.  @jamshale -- can you please investigate.

Errors:

```
Failing scenarios:
  features/0453-issue-credential.feature:321  Issue a credential with revocation, with the Issuer beginning with an offer, and then revoking the credential -- @1.3 
  features/0454-present-proof.feature:138  Present Proof where the issuer revokes the credential and the proof fails -- @1.1 
  features/0454-present-proof.feature:143  Present Proof where the issuer revokes the credential and the proof fails -- @2.1 
  features/0454-present-proof.feature:204  Present Proof for multiple credentials where the one is revocable and one isn't, neither credential is revoked -- @1.1 
  features/0454-present-proof.feature:262  Present Proof for multiple credentials where the one is revocable and one isn't, and the revocable credential is revoked, and the proof checks for revocation and fails -- @1.1 
  features/0454-present-proof.feature:263  Present Proof for multiple credentials where the one is revocable and one isn't, and the revocable credential is revoked, and the proof checks for revocation and fails -- @1.2 
  features/0586-sign-transaction.feature:107  endorse a schema and cred def transaction, write to the ledger, issue and revoke a credential, manually invoking each endorsement endpoint -- @1.1 
  features/revocation-api.feature:42  Using revocation api, issue, revoke credentials and publish -- @1.1 
  features/revocation-api.feature:44  Using revocation api, issue, revoke credentials and publish -- @1.3 
```

I notice all the failures are with revocable credentials -- issue and present.  I can't think of where that might be breaking but...

**Comment by swcurran** [comment]
Looks like it is a tails file issue -- although I would think that would affect the non-revocation tests as well. There must be some, right?

```
7hAcme.agent | aries_cloudagent.revocation.error.RevocationError: Tails file for rev reg HsWgudheR1Wa3tBhJW6xJt:4:HsWgudheR1Wa3tBhJW6xJt:3:CL:1532186:Acme.agent.initial.129198.Schema_DriversLicense:CL_ACCUM:fd0dd658-0976-4a9f-887c-5ba5d9010ace failed to upload: Exceeded maximum upload attempts
```

**Comment by jamshale** [comment]
Same problems as the nightly fail. Looks like both issues with the tails server and ledger. I guess re-booting it didn't work :/

**Comment by esune** [comment]
I rebooted the tails server now, I don;t think I did this morning. We need to figure out what is causing that poisoned lock there, i will log an issue that we can tackle.

**Pull request merged**
