### PR TITLE
Updates in Connection Record and Connection APIs for Issue #736

### PR DESCRIPTION
**Pull request by ankita-p17**
Updates in Connection Record and APIs to accomodate changes specific to below issue for Sign Transaction Protcol 

https://github.com/hyperledger/aries-cloudagent-python/issues/736

Reference : 
https://hackmd.io/5LzMhfsMQBevB5V2tKz4hA?view

@swcurran @andrewwhitehead @ianco please check

### CODE REVIEW

**Comment by ianco** [comment]
Hi @ankita-p17 please make sure to DCO sign your commits, see:  https://github.com/hyperledger/aries-cloudagent-python/pull/774/checks?check_run_id=1351780206

**Comment by ankita-p17** [comment]
> Hi @ankita-p17 please make sure to DCO sign your commits, see: https://github.com/hyperledger/aries-cloudagent-python/pull/774/checks?check_run_id=1351780206
> 
> (Also make sure to double-check unit tests are passing, including the code formatting)

Done. can you check the changes made

**Comment by ianco** [comment]
Hi @ankita-p17 the DCO check is still failing.  In the past when this has happened to me sometimes the fix they recommend doesn't work (you can see the commits in the commit history still have a red "x" next to them).  Sometimes I've had to create a new branch and move my code over to get a clean commit history.

Make sure you always `--signoff` on every commit.  I think you can setup your local git configuration so that this is the default.

**Comment by andrewwhitehead** [comment]
I don't think we want to do this by extending the Connection record with information that isn't specific to the connection. We would need to add a new stored record to capture it.

**Comment by ankita-p17** [comment]
> I don't think we want to do this by extending the Connection record with information that isn't specific to the connection. We would need to add a new stored record to capture it.

Non-indy roles should be captured as another record? So for every connection, there will be different records maintained if user opt for role transaction Author, right?

**Comment by sklump** [comment]
A connection record is meant to represent an RFC 160 (or, soon, RFC 23) connection between agents.

**Comment by ankita-p17** [comment]
> A connection record is meant to represent an RFC 160 (or, soon, RFC 23) connection between agents.

Got it

**Comment by ankita-p17** [comment]
Duplicate of #799 which has more functionalities for the protocol

**Pull request closed without merging**
