### PR TITLE
:bug: fix storage record pagination with post-filter query params

### PR DESCRIPTION
**Pull request by ff137**
Related to: https://github.com/hyperledger/aries-cloudagent-python/issues/3001#issuecomment-2206110085

Marking as draft to first validate things work as expected (testing here: https://github.com/didx-xyz/aries-cloudapi-python/pull/850)

### CODE REVIEW

**Review by jamshale — APPROVED** [review]
Looks good :+1: 

Sonarcloud is saying it's a bit complicated and could be refactored but it looks well tested so I'm not worried about that right now.

**Comment by ff137** [comment]
Oof, I was just about to commit a change to make it more readable 😅

**Comment by ff137** [comment]
No prob, I'll make another PR with some minor amendments, also improving the error handling which is prob worth it

**Comment by jamshale** [comment]
Ok. Sorry about that. Another PR will be good.

**Comment by ff137** [comment]
All good, I was slow 😄 included the changes in #3083

**Pull request merged**
