### PR TITLE
Restore initiator to conn rec nominally

### PR DESCRIPTION
**Pull request by sklump**

### CODE REVIEW

**Comment by sklump** [comment]
Addresses https://github.com/hyperledger/aries-cloudagent-python/issues/958

**Comment by andrewwhitehead** [comment]
It looks like the reported error was going through the `from_storage` class method, which seems to bypass the schema – we probably want to adjust that later but there may be a reason it works that way. I added the `rfc23_state` parameter because it was also causing an issue once I adjusted the test.

**Review by andrewwhitehead — APPROVED** [review]

**Comment by sklump** [comment]
I don't understand how rfc23_state could get into the record. It's neither a tag nor a value. It's a bit of a worry.

**Comment by sklump** [comment]
Enforcing the schema through `from_storage()` will wreck a lot of the unit tests as many throwaway records are missing mandatory fields. Doable but not a quick fix.

**Pull request merged**
