### PR TITLE
Add did web method type as a default option

### PR DESCRIPTION
**Pull request by PatStLouis**
Addresses issue #2667.

Inspired by the [did methods documentation](https://github.com/hyperledger/aries-cloudagent-python/blob/main/DIDMethods.md).

### CODE REVIEW

**Comment by swcurran** [comment]
@PatStLouis — please check the Lint test failure.

@dbluhm — what do you think of this?  OK as a start?

**Comment by PatStLouis** [comment]
I tested issuance/verification in both single tenant/multitenant modes.

I had a strange error with verification at first but I'm unable to reproduce it....verification works now using a `did:web` issuer...I'll keep an eye out, here's the error the verification endpoint was returning
`
('Could not expand input before framing.',)\nType: jsonld.FrameError\nCause: ('Tried to nullify a context with protected terms outside of a term definition.',)\nType: jsonld.SyntaxError\nCode: invalid context nullification  File \"/home/aries/.local/lib/python3.9/site-packages/pyld/jsonld.py\", line 1032, in frame\n    expanded = self.expand(input_, options)\n  File \"/home/aries/.local/lib/python3.9/site-packages/pyld/jsonld.py\", line 870, in expand\n    expanded = self._expand(active_ctx, None, document, options,\n  File \"/home/aries/.local/lib/python3.9/site-packages/pyld/jsonld.py\", line 2329, in _expand\n    self._expand_object(\n  File \"/home/aries/.local/lib/python3.9/site-packages/pyld/jsonld.py\", line 2728, in _expand_object\n    expanded_value = self._expand(\n  File \"/home/aries/.local/lib/python3.9/site-packages/pyld/jsonld.py\", line 2233, in _expand\n    e = self._expand(\n  File \"/home/aries/.local/lib/python3.9/site-packages/pyld/jsonld.py\", line 2324, in _expand\n    active_ctx = self._process_context(\n  File \"/home/aries/.local/lib/python3.9/site-packages/pyld/jsonld.py\", line 3076, in _process_context\n    raise JsonLdError(\n"
`

**Comment by PatStLouis** [comment]
I think I found the issue, it seems to be related with the [traceability context url](https://w3id.org/traceability/v1). Trying to verify a vc issued by a `did:web` issuer who has this context included in it's did document seems to raise this strange error. Here's a vc to test (can be verified with other verification services such as the [univerifier](https://univerifier.io/)). Verifying the same vc without the traceability context returns true in aca-py.
```
{
        "@context": [
            "https://www.w3.org/2018/credentials/v1"
        ],
        "id": "urn:uuid:31288134-1c6a-42a2-aa37-c5c38dea09c0",
        "type": [
            "VerifiableCredential"
        ],
        "issuer": "did:web:PatStLouis.github.io",
        "issuanceDate": "2023-12-19T01:13:13.401Z",
        "credentialSubject": {
            "id": "did:example:123"
        },
        "proof": {
            "type": "Ed25519Signature2018",
            "proofPurpose": "assertionMethod",
            "verificationMethod": "did:web:PatStLouis.github.io#verkey",
            "created": "2023-12-19T01:13:13.401Z",
            "jws": "eyJhbGciOiAiRWREU0EiLCAiYjY0IjogZmFsc2UsICJjcml0IjogWyJiNjQiXX0..ahIwxPaTgLmUS4aS9nFApVQmx-uklAAR0I-W_-IKzhvMQFmCl0g7etQw3DG8oKqVs-0hlewuCtUxKZGO1GyyBw"
        }
    }
```

**Comment by swcurran** [comment]
That is quite an `@context` file!!

ACA-Py is now pre-loading contexts — I wonder if that is the issue.  This was recently added in PR #2587 that is part of 0.11.0.  It might be worth trying 0.10.5 to see if the same issue occurs.  Given the pre-loading of context, I’m not sure how contexts that are not pre-loaded are handled.  I assume they are loaded dynamically, but that is not considered “best practice” in JSON-LD land, so perhaps not.  Which of course leads to the question, how does one add ones own contexts to an instance of ACA-Py?

**Comment by PatStLouis** [comment]
I tried [adding and caching the context in the document loader](https://github.com/OpSecId/aries-cloudagent-python/blob/19e02bfaf4f6c5d2b2790edb783d0f009de546c7/aries_cloudagent/vc/ld_proofs/document_downloader.py#L45) as well and get the same result. Also putting the agent in debug mode doesn't log any errors so this seem unhandled from the `pyld` package. I'm going to try and find out where in the code this verification fails. Now the did core spec **recommends** having a context file for your services, its not required so this won't prevent any test cases AFAIK. The [issue raised](#2677) about the `service.type` being an array does get tested. I'll have a look at the `PyDID` library like @dbluhm suggested to understand the impact.

```
// Service array is used to look up traceability API service endpoint
pm.test("Response must include 'service' array", function() {
    const { service } = pm.response.json().didDocument;
    pm.expect(service).to.be.an('array').that.is.not.empty;
});
```

**Comment by swcurran** [comment]
@PatStLouis -- can you please check on the conflicts?

**Comment by PatStLouis** [comment]
fixed the conflict between the did:peer and did:web wallet methods

**Review by swcurran — APPROVED** [review]

**Pull request merged**
