### PR TITLE
Increase promote did retries

### PR DESCRIPTION
**Pull request by jamshale**
Doh! I think I must have accidentally deleted the wait in between retries somehow and not noticed.

Hopefully this should prevent the errors during promote did.

### CODE REVIEW

**Review by swcurran — APPROVED** [review]

**Comment by swcurran** [comment]
Test fail is super interesting — a CredDef that is attempting to be published fails because it already exists on the ledger.  I checked the ledger and `N1LoA9rMwyskHEW9csYpQJ:3:CL:360946:Faber.agent.Schema_DriversLicense_v2` was created on Feb. 16 — http://test.bcovrin.vonx.io:3707/tx/BCOVRIN_TEST/domain/360950.

How does that happen?  That means that the DID being used in the test was the same as being used on Feb. 16.

🤯

**Comment by jamshale** [comment]
> Test fail is super interesting — a CredDef that is attempting to be published fails because it already exists on the ledger. I checked the ledger and `N1LoA9rMwyskHEW9csYpQJ:3:CL:360946:Faber.agent.Schema_DriversLicense_v2` was created on Feb. 16 — http://test.bcovrin.vonx.io:3707/tx/BCOVRIN_TEST/domain/360950.
> 
> How does that happen? That means that the DID being used in the test was the same as being used on Feb. 16.
> 
> 🤯

That's the other fail I've seen. Not as often. 

Feb 16. That doesn't make any sense???

**Comment by swcurran** [comment]
The only thing I can think of is that the same seed for the DID was generated on both test runs.  Is it possible we’re not being random enough when coming up with the seed?

**Comment by jamshale** [comment]
I just had another fail like this `69HTqHL7PjCS8K4Bp44g46:3:CL:293648:Faber.agent.Schema_DriversLicense_v2` from Jan 29. Seems like the tests must be recreating the same dids :/

**Pull request merged**
