### PR TITLE
Docker images and GHA for publishing images

### PR DESCRIPTION
**Pull request by dbluhm**
This PR is a reopening of #1888 and still contains some of the issues discussed on that PR. If someone wants to tackle some of those issues (whether actually using this branch or just taking inspiration -- either way is fine with me!), I'd be happy to see this fixed up and working.

cc @WadeBarnes @swcurran

### CODE REVIEW

**Comment by dbluhm** [comment]
> It looks like there are still some bugs to workout with the images published with the workflows that are triggered by a release. The images are still getting overwritten, as they are not getting tagged with the python version or -indy tag.
>
> References:
>
> - https://github.com/WadeBarnes/aries-cloudagent-python/actions/runs/3743057801
> - https://github.com/WadeBarnes/aries-cloudagent-python/actions/runs/3743058781
> - https://github.com/WadeBarnes/aries-cloudagent-python/actions/runs/3743062864
> - https://github.com/WadeBarnes/aries-cloudagent-python/actions/runs/3743062872
> - https://github.com/WadeBarnes/aries-cloudagent-python/pkgs/container/aries-cloudagent-python/versions

**Comment by WadeBarnes** [comment]
Thanks @dbluhm

**Comment by WadeBarnes** [comment]
Tagging myself as an assignee, but others are free to help out too.

**Comment by WadeBarnes** [comment]
Latest commit fixes the release and workflow_dispatch triggered runs so the expected images and image tags are created.  I've also limited the builds to py3.6 (for legacy) and py3.9.  I'd consider this a good first pass an the image builds.  An enhancement would be to include the tests for each python version and gate the image creation and publishing based on the tests passing.

Test runs of each of the workflows and triggers can be found here:
- https://github.com/WadeBarnes/aries-cloudagent-python/actions/runs/3915440665
- https://github.com/WadeBarnes/aries-cloudagent-python/actions/runs/3915440061
- https://github.com/WadeBarnes/aries-cloudagent-python/actions/runs/3915432356
- https://github.com/WadeBarnes/aries-cloudagent-python/actions/runs/3915432351

Resulting images can be found here:
- https://github.com/WadeBarnes/aries-cloudagent-python/pkgs/container/aries-cloudagent-python/versions

The resulting images have not been tested yet.

**Comment by swcurran** [comment]
Looks good!  What do the tags on the images indicate?  E.g. the `tm-11` and `1.0.0-rc18`?

**Comment by WadeBarnes** [comment]
> Looks good! What do the tags on the images indicate? E.g. the `tm-11` and `1.0.0-rc18`?

The `tm-11` tag was one I used when testing the manually triggered workflow runs.
image

The `1.0.0-rc18` tag is the result of creating a release to test the release triggered workflow; https://github.com/WadeBarnes/aries-cloudagent-python/releases/tag/1.0.0-rc18

**Comment by WadeBarnes** [comment]
The latest commits add support for mutil-platform images.  Images include support for `amd64`, `arm64`, and `i386`.  The ACA-Py with Indy SDK images do not support `arm64` for the reasons noted in [.github/workflows/publish-indy.yml](https://github.com/hyperledger/aries-cloudagent-python/pull/2076/files#diff-e3fa2c515460e1165384b9fa37c9fd91b9f9309b42bc649291729b9fcecd77e6)

**Comment by WadeBarnes** [comment]
I'd say this PR is ready for review.  Once merged we should add a ticket to track the enhancement to add the gating tests as described here; https://github.com/hyperledger/aries-cloudagent-python/pull/2076#issuecomment-1382579089

**Review by ianco — APPROVED** [review]

**Comment by WadeBarnes** [comment]
Great, I'll add the ticket to track adding the tests.

**Comment by WadeBarnes** [comment]
Issue to track the addition of the unit tests; https://github.com/hyperledger/aries-cloudagent-python/issues/2085

**Pull request merged**
