### PR TITLE
BREAKING: feat: get queued outbound message in transport handle message

### PR DESCRIPTION
**Pull request by dbluhm**
This will enable queues to annotate outbound messages with relevant context for things like dead letter queues that know which wallet sent the message that failed, what message was being sent, etc.

This is a breaking change for plugins adding queue implementations (cc @shaangill025) but we think this is worthwhile for the ability to improve internal error handling.

### CODE REVIEW

**Comment by dbluhm** [comment]
This can wait (sorry for the slow response and glad you didn't wait on me lol)

**Comment by dbluhm** [comment]
@swcurran I'd like to see this PR merged but I think the breaking change status has scared us away from merging so far :sweat_smile: To reiterate, this breaking change affects only message queue plugins and will not affect deployments not using these plugins. For message queue plugins, the required modifications should be pretty minimal; we have a branch for the Kafka plugin already that incorporates this change. Updating the Redis plugin should be pretty trivial.

**Comment by swcurran** [comment]
@dbluhm -- shall we merge this one next?  @usingtechnology, @Jsyro, @shaangill025 -- who is the best to coordinate what changes need to be made to the plugins for Redis once this is merged.

**Comment by usingtechnology** [comment]
i guess it will depend on workloads. if @shaangill025 is busy, i could probably jump in and tackle it. do we know if the redis queue plugin is in production anywhere?

**Comment by swcurran** [comment]
Please do.  We’re pushing on getting a bunch of merges done now that we have 0.8.2 out the door.

**Comment by shaangill025** [comment]
I think the changes in Redis plugin to work with this PR will involve the following:
https://github.com/bcgov/aries-acapy-plugin-redis-events/blob/a27cefe5de1b8e74e3c154bf9c782b6dcb4b464b/redis_queue/v1_0/outbound.py#L63
```
async def handle_message(
      self,
      profile: Profile,
      outbound_message: QueuedOutboundMessage,
      endpoint: str,
      metadata: dict = None,
      api_key: str = None,
  ):
      """Prepare and send message to external queue."""
      payload = outbound_message.payload
```

Also adding `QueuedOutboundMessage` import [here](https://github.com/bcgov/aries-acapy-plugin-redis-events/blob/a27cefe5de1b8e74e3c154bf9c782b6dcb4b464b/redis_queue/v1_0/outbound.py#L9)

**Comment by dbluhm** [comment]
As @shaangill025 outlined, changes were pretty minimal so I went ahead and opened a PR with those changes over there.

**Comment by dbluhm** [comment]
> Please do. We’re pushing on getting a bunch of merges done now that we have 0.8.2 out the door.

A little unclear to me: are there external dependencies blocking this PR specifically or can we go ahead and merge?

**Comment by swcurran** [comment]
No.  We’ll merge.  We are also going to do a tag on the Redis plugin on the commit before merging this one to point out the breaking change.

**Pull request merged**
