### PR TITLE
Endpoint type merge

### PR DESCRIPTION
**Pull request by sklump**
Merge current master into Dominic Wörner's PR#589 (which became #634) endpoint-type work en route to merging back into master, unit test coverage

### CODE REVIEW

**Comment by sklump** [comment]
Merges current master into https://github.com/hyperledger/aries-cloudagent-python/pull/634 in preparation for merge of this (endpoint-type) work back into aca-py master.

**Comment by domwoe** [comment]
Thanks!

**Comment by domwoe** [comment]
> Is there a need to allow for provisioning with different endpoint types? Since only `endpoint_type==EndpointType.ENDPOINT` affects the wallet, I am guessing that there is no such need?

This could make sense. In particular if you want to do all ledger operations during provisioning

**Comment by sklump** [comment]
> 
> 
> > Is there a need to allow for provisioning with different endpoint types? Since only `endpoint_type==EndpointType.ENDPOINT` affects the wallet, I am guessing that there is no such need?
> 
> This could make sense. In particular if you want to do all ledger operations during provisioning

I think that could be separate PR though. This one introduces a significant change on its own. I can get on it once it's merged.

**Pull request merged**
