### PR TITLE
added logging documentation

### PR DESCRIPTION
**Pull request by chriamue**
Added markdown documentation of logging in Acapy.

- [x] Command Line Arguments
- [x] Environment Variables
- [x] Acapy Config
- [x] Logging Config File
- [x] Link in dev readme

### CODE REVIEW

**Comment by chriamue** [comment]
Whats the best location for Logging.md file?

**Comment by swcurran** [comment]
I think the root is probably fine for now, as others are there.  We should probably put them into docs, but I think we need to do them all together.

The question is where we want to put the link to this file. I think it should go into the DevReadme.md file at some useful point.

@ianco -- please take a read through this for accuracy and to approve.

Thanks for the contribution -- good stuff.

**Comment by ianco** [comment]
> The question is where we want to put the link to this file. I think it should go into the DevReadme.md file at some useful point.

Yes looks good thanks for the PR.  I suggest to link from `docs/logging/docs/GettingStartedAriesDev` somewhere?

**Comment by swcurran** [comment]
I would think that this section of the Developer's ReadMe would be best -- https://github.com/hyperledger/aries-cloudagent-python/blob/main/DevReadMe.md#developing

**Review by swcurran — APPROVED** [review]
LGTM -- Thanks!

**Pull request merged**
