### PR TITLE
Relax formats rfcs 453 454

### PR DESCRIPTION
**Pull request by sklump**
Ignore unrecognized formats rather than rejecting their messages

### CODE REVIEW

**Review by TimoGlastra — COMMENTED** [review]
Nice!

Small note, I think the `attachment()` methods (e.g. in cred_request.py) should also be modified as the `V20CredFormat.Format.get` could return None

**Comment by sklump** [comment]
I should get to it later today. I will include it here and ping you again @TimoGlastra before I merge it

**Comment by sklump** [comment]
@TimoGlastra how about now? I think this is better overall - in any list of formats, getting an attachment without specifying a format picks the first recognized rather than trying what's at index zero.

**Review by TimoGlastra — COMMENTED** [review]
Perfect!

**Review by andrewwhitehead — APPROVED** [review]

**Pull request merged**
