### PR TITLE
Connectionless proof demo

### PR DESCRIPTION
**Pull request by ianco**

### CODE REVIEW

**Comment by ianco** [comment]
Also fixes issue https://github.com/hyperledger/aries-cloudagent-python/issues/1291

**Review by swcurran — APPROVED** [review]
A couple of things that would be nice to change, but not holding it up because of them:

1. It would be nice if Alice accepted the invitation and processed the connectionless proof, either be making the existing “new invitation” fancier or by adding a new option.

2. It would be nice that instead of hard-coding the predicate dateIn value, that you showed the calculation to get the date — e.g. convert_to_dateInt(now() -years(21)).

**Comment by ianco** [comment]
> A couple of things that would be nice to change, but not holding it up because of them:
> 
> 1. It would be nice if Alice accepted the invitation and processed the connectionless proof, either be making the existing “new invitation” fancier or by adding a new option.
> 2. It would be nice that instead of hard-coding the predicate dateIn value, that you showed the calculation to get the date — e.g. convert_to_dateInt(now() -years(21)).

Re #2, I'll update in my next PR.

Re #1, I'm not sure what this means, since it's a connectionless proof ...

**Comment by swcurran** [comment]
Re: 1 — A connection-less proof is just an invitation (plain-text) given to an any agent to which they respond (if they want, of course) with a proof.  Alice could be that agent — separate from her existing connection with Faber.  So her agent just gets the invitation with the proof request and responds to it using the data in the invitation, without really knowing who is asking.

**Pull request merged**
