### PR TITLE
Fixes for TAA and public invite

### PR DESCRIPTION
**Pull request by dbluhm**
We ran into a couple of small issues recently; hopefully these are acceptable fixes.

### CODE REVIEW

**Comment by andrewwhitehead** [comment]
@dbluhm What is the goal in adding the endpoint to the public invitation? It's not clear to me that doing that is even supported in the spec. Always adding it certainly doesn't seem necessary as it can be looked up on the ledger.

**Comment by dbluhm** [comment]
Ah, that's mostly a hack so that the invite URL will be correctly formatted. Without it, it comes out as `?c_i=<invite b64>`. I can remove that commit as it's obviously not a permanent fix.

**Comment by dbluhm** [comment]
There's another issue that I discovered. I fixed it but need to push (hopefully sometime this weekend or monday morning) for TAA. The current timestamps added to the TAA are too accurate and are rejected by the ledger.

**Comment by dbluhm** [comment]
Removing some of the extra bits and reopening as a separate PR. Thanks for the feedback!

**Pull request closed without merging**
