### PR TITLE
Fix: Inbound Transport is_external attribute

### LINKED ISSUE #1790: Issues with aries-acapy-plugin-toolbox when updating to 0.7.4
While updating https://github.com/hyperledger/aries-acapy-plugin-toolbox from 0.7.4 RC0 to 0.7.4 RC2, multiple errors have been encountered in the integration tests. I am still digging in to what these issues are, the only one that I remember off of the top of my head is related to #1659. A new attribute was added to the base inbound transport (and the default was added then removed) and it appears to be a required attribute.

### LINKED ISSUE #1791: Inbound Transport now has an undocumented, required attribute is_external
As mentioned in #1790, PR #1659 has introduced a new required attribute `is_external`. While going through the history, I noticed that in the PR, a default was set and then removed later on in this commit: https://github.com/hyperledger/aries-cloudagent-python/commit/577f34a48daea5b3c87705ab84f4f7e722afeedf#r74716748

This change caused the `HttpWsTransport` in https://github.com/hyperledger/aries-acapy-plugin-toolbox to break on startup (indicating a breaking change) due to the use of `is_external` in other parts of the code.

### PR DESCRIPTION
**Pull request by shaangill025**
Signed-off-by: shaangill025 [gill.shaanjots@gmail.com](mailto:gill.shaanjots@gmail.com)

- resolve #1790 
- resolve #1791

Closed original PR #1792 due to merge issues.

### CODE REVIEW

**Comment by swcurran** [comment]
This is a redo of a previous PR.  Please review.  @shaangill025 -- let us know about the "Draft" status and when that is removed.

Anxious to get this into the release.

**Comment by andrewwhitehead** [comment]
LGTM

**Review by frostyfrog — APPROVED** [review]
These changes look good to me. The only comment that I had was about adding a "Inbound/Outbound Transports" label right next to the "External Plugin" label, but the internal lists are going to typically be fairly small so I don't think it's necessary. Great work!

**Review by swcurran — APPROVED** [review]
Per review from @frostyfrog -- good to go.

**Pull request merged**
