### PR TITLE
feat: add new format and implement VCDICredFormatHandler (Draft)

### PR DESCRIPTION
**Pull request by tra371**
- add `VC_DI` in `CredFormat.Format`
- lay out `VCDICredFormatHandler`
- add new schema classes for cred offer and request
- implement CredExRecordVCDI
- fix schemas on cred_abstract and cred_request, improve on vc_di support on alice-faber demo

next step
- fix unittests issues

### CODE REVIEW

**Comment by ianco** [comment]
@tra371 overall looks good.  If you need a hand with the test let me know, I can show you how to run everything locally to help track down some of the errors that are getting reported.  (I know the code is in progress but it's a good idea to keep on top of these.)

Also you can flag the PR as "in draft" if it's not yet ready to merge,

**Comment by tra371** [comment]
> @tra371 overall looks good. If you need a hand with the test let me know, I can show you how to run everything locally to help track down some of the errors that are getting reported. (I know the code is in progress but it's a good idea to keep on top of these.)
> 
> Also you can flag the PR as "in draft" if it's not yet ready to merge,

thank you @ianco yes that would be great if you could give me a pointer on that.. let us discuss more on discord

**Comment by ianco** [comment]
Looks like the faber demo was updated, can you update the faber doc (or even just add a comment to this PR) listing the parameters you use to run faber?

**Comment by tra371** [comment]
> Looks like the faber demo was updated, can you update the faber doc (or even just add a comment to this PR) listing the parameters you use to run faber?
> 
> (I tried this `./run_demo faber --wallet-type askar-anoncreds --cred-type vc_di` but it gives me an error `Exception: Invalid credential type:vc_di`)

ok i'm on it

**Comment by ianco** [comment]
When I run the demo (after making the changes locally that I mentioned in comments) I get the following error when trying to issue a credential from faber to alice:

```
$ AGENT_PORT_OVERRIDE=8010 ./run_demo faber --wallet-type askar-anoncreds --cred-type vc_di
... (paste the invite from faber to alice, then select option "1" to issue the credential) ...
[1/2/3/4/T/X] 1                                                                                                                                                                                                  

#13 Issue credential offer to X
Faber      | 2024-02-20 18:44:17,298 aries_cloudagent.admin.server ERROR Handler error with exception: Unprocessable Entity
Faber      |Shutting down agent ...
 Faber      | Traceback (most recent call last):

Faber      |   File "/home/aries/.local/lib/python3.9/site-packages/webargs/asyncparser.py", line 90, in parse
Faber      |Faber      |     result = schema.load(parsed)
 Faber      |   File "/home/aries/.local/lib/python3.9/site-packages/marshmallow/schema.py", line 723, in load
=================
Faber      |     return self._do_load(
Faber      |   File "/home/aries/.local/lib/python3.9/site-packages/marshmallow/schema.py", line 910, in _do_load
Faber      |     raise exc
Faber      | marshmallow.exceptions.ValidationError: {'filter': {'_schema': ['V20CredFilterSchema requires indy, ld_proof, or both']}}
Faber      | 
Faber      | During handling of the above exception, another exception occurred:
Faber      | 
Faber      | Traceback (most recent call last):
Faber      |   File "/home/aries/aries_cloudagent/admin/server.py", line 181, in ready_middleware
Faber      |     return await handler(request)
Faber      |   File "/home/aries/aries_cloudagent/admin/server.py", line 218, in debug_middleware
Faber      |     return await handler(request)
Faber      |   File "/home/aries/aries_cloudagent/admin/server.py", line 451, in setup_context
Faber      |     return await task
Faber      |   File "/usr/local/lib/python3.9/asyncio/futures.py", line 284, in __await__
Faber      |     yield self  # This tells Task to wait for completion.
Faber      |   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 328, in __wakeup
Faber      |     future.result()
Faber      |   File "/usr/local/lib/python3.9/asyncio/futures.py", line 201, in result
Faber      |     raise self._exception
Faber      |   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 256, in __step
Faber      |     result = coro.send(None)
Faber      |   File "/home/aries/.local/lib/python3.9/site-packages/aiohttp_apispec/middlewares.py", line 33, in validation_middleware
Faber      |     data = await request.app["_apispec_parser"].parse(
Faber      |   File "/home/aries/.local/lib/python3.9/site-packages/webargs/asyncparser.py", line 94, in parse
Faber      |     await self._on_validation_error(
Faber      |   File "/home/aries/.local/lib/python3.9/site-packages/webargs/asyncparser.py", line 108, in _on_validation_error
Faber      |     await error_handler(error, req, schema, error_status_code, error_headers)
Faber      |   File "/home/aries/.local/lib/python3.9/site-packages/webargs/aiohttpparser.py", line 163, in handle_error
Faber      |     raise error_class(
Faber      | aiohttp.web_exceptions.HTTPUnprocessableEntity: Unprocessable Entity
Faber      | 
Faber      | Shutting down
Faber      | Exited with return code 0
```

I'll open a PR to your repo with the changes I made locally

**Comment by ianco** [comment]
> I'll open a PR to your repo with the changes I made locally

OK I can't open a PR to your repository for some reason, however you can see the changes I made locally (to get the DID and schema registration to work) here:

https://github.com/ianco/aries-cloudagent-python/commit/dfebc768a0af1066661453692d0c7afe2dddf8dc

**Comment by tra371** [comment]
> > I'll open a PR to your repo with the changes I made locally
> 
> OK I can't open a PR to your repository for some reason, however you can see the changes I made locally (to get the DID and schema registration to work) here:
> 
> [ianco@dfebc76](https://github.com/ianco/aries-cloudagent-python/commit/dfebc768a0af1066661453692d0c7afe2dddf8dc)

thank you so much, @ianco.. i've applied these updates

**Comment by gvelez17** [comment]
> > I'll open a PR to your repo with the changes I made locally
> 
> OK I can't open a PR to your repository for some reason, however you can see the changes I made locally (to get the DID and schema registration to work) here:
> 
> [ianco@dfebc76](https://github.com/ianco/aries-cloudagent-python/commit/dfebc768a0af1066661453692d0c7afe2dddf8dc)

@sarthakvijayvergiya ^^ make sure we cleanly included this

**Comment by gvelez17** [comment]
hey guys, partly my fault for an old unsigned commit, but also the commit history here has gotten muddy.  I cherry-picked all our commits in our branch and replayed on main and squashed, made a new PR over here: https://github.com/hyperledger/aries-cloudagent-python/pull/2830

I think it will be better to merge that one, otherwise rebases are going to be evil

**Comment by ianco** [comment]
New version of PR is here:  https://github.com/hyperledger/aries-cloudagent-python/pull/2830

**Pull request closed without merging**
