### PR TITLE
WIP : Script and first run output to show when Open API changes

### PR DESCRIPTION
**Pull request by jcourt562**
Signed-off-by: john court <jcourt@anonyome.com>

### CODE REVIEW

**Comment by jcourt562** [comment]
This pull request provides a script to generate the openapi.json spec file from a running ACA-py.  The openapi.json can be checked in and used to compare in subsequent releases for unexpected changes.   Apart from explicit changes to the REST API the only changes should be the random/timestamp related "example" fields in the spec file.  This submit is in response to issue #742

**Review by WadeBarnes — COMMENTED** [review]
I'd recommend refactoring `waitActiveWebInterface` to function along the lines of https://github.com/hyperledger/aries-agent-test-harness/blob/master/manage#L279.  That way you get a status indication in cases where the container takes a bit of time to spin up.

**Comment by ianco** [comment]
How does this sort the output openapi.json file?

I tried running the script and the file I generated was in a completely different order than the checked-in file (so there were a lot of spurious differences between the files).

**Comment by jcourt562** [comment]
It doesn't sort the output at all, or shouldn't.  The intent is that the output coming from ACA-py is already sorted.  This was the intent of the script to detect changes.  I have run it many times but maybe there is something specific to my installation.  Can I ask what version of ACA-py you are running it against ?  as prior to V0.5.6 you may well see issues since this is why the script was created.

**Comment by ianco** [comment]
I have the latest master branch checked out, and I merged the code from this PR.

**Comment by swcurran** [comment]
@ianco -- the idea for this came about because of @sklump 's change to make the openapi.json file come out sorted already. If that is not working, we need to look at where it is coming from.  Perhaps that feature was lost somewhere?

**Comment by ianco** [comment]
@swcurran  what's the PR?  I'll check to make sure it's included in my local ...

**Comment by swcurran** [comment]
Looks like it is #738.

**Comment by ianco** [comment]
ok that's definitely included in my local

**Comment by jcourt562** [comment]
Can you post the output you are seeing ?   I may be able to tell what is happening based on what the differences are and having seen the wrong behaviour from ACA-py previously.   So the only other possibility is that the swagger codegen for some reason outputs different openapi.json randomly from the same raw swagger.json from ACA-py.  I haven't seen this to date and in particular there are options to swagger to artificially sort which we intentionally aren't using because that would cause other problems around detecting ACA-py changes.

**Comment by jcourt562** [comment]
So I just pulled up to the latest master and re-ran, it behaved as expected but one thing I realised is that if you are already running an ACA-py on your local machine, its possible the script will fail to start its own and instead end up pulling the swagger file from the pre-existing instance.  @ianco is this a possibility with your environment ?  I would still like to see your openapi.json but will make sure the script exits if the ACA-py start phase fails.  I will also change the admin port to be a non-standard one everyone seems to use so that there is less chance of connection to an existing instance by mistake.

**Comment by ianco** [comment]
I made sure everything was shut down and re-ran the script, the output was the same.  (It's possible another aca-py was running when I tested this earlier, I'm not sure.)

Here's my output:

[openapi.json.zip](https://github.com/hyperledger/aries-cloudagent-python/files/5531070/openapi.json.zip)

**Comment by ianco** [comment]
FYI the api list on the swagger page is now sorted (according to the PR that @swcurran referenced) however the generated opeapi json file is not.  It looks like the file you generate (checked into your PR) is different from mine, and neither are sorted the same as the swagger page.

**Comment by jcourt562** [comment]
Yep, it looks like there is an issue with swagger not maintaining the order of paths from the raw input.  The actual issues I had filed previously were around parameter order and object model order since they caused me wrapper code breakages.  I don't understand why it has consistently created the same output for me so I didn't see the issue (in fact I didn't even realise ACA-py was also sorting paths).  It could be as simple as different CPU speeds or timezone affecting internal ordering.    The sad thing is that it doesn't look like either OpenAPI or Swagger code generators have really addressed this issue so I might have to look at a different approach to formatting the "raw" interface file from ACA-py Into something more diff friendly. Will investigate.

**Comment by jcourt562** [comment]
@ianco I just need to challenge your assertion that the raw swagger output from ACA-py is sorting the paths ?  I took the raw output and feed it through an online JSON pretty printer and the result doesn't show paths sorted in any meaningful way ?
I went through the painful process of checking the first few hadn't changed order between raw and the pretty format.  Attaching pretty format file.
[jsonformatter.txt](https://github.com/hyperledger/aries-cloudagent-python/files/5533640/jsonformatter.txt)

**Comment by jcourt562** [comment]
I have also just gone through #738.  That seems to be sorting swagger_dict["definitions"]  I don't see anywhere in the code where swagger_dict["paths"] gets sorted, I do see parameters within paths being sorted.

**Comment by ianco** [comment]
I haven't looked into the underlying files, so possibly you're right.

In the displayed swagger page (i.e. in the browser) everything is displayed sorted by message type and then path, I don't know where all this sorting is taking place.

Screen Shot 2020-11-12 at 3 38 33 PM

**Comment by jcourt562** [comment]
I suspect it must be happening in the web server part of the code not in the core.

**Comment by ianco** [comment]
> I have also just gone through #738. That seems to be sorting swagger_dict["definitions"] I don't see anywhere in the code where swagger_dict["paths"] gets sorted, I do see parameters within paths being sorted.

It sorts recursively, "asciibetically", so paths will get sorted within definitions etc.

https://github.com/hyperledger/aries-cloudagent-python/pull/738/files#diff-f3648d939ba43f8f8b8a42f8786f921dd598def57267dd9e3904a3a9ff391d6dR348

**Comment by jcourt562** [comment]
@ianco how do you come to that conclusion ? They are seperate dictionaries aren't they ?  I assume definitions are the model definitions : 

       # order tags alphabetically, parameters deterministically and pythonically
        swagger_dict = self.app._state["swagger_dict"]
        swagger_dict.get("tags", []).sort(key=lambda t: t["name"])
        for path in swagger_dict["paths"].values():
            for method_spec in path.values():
                method_spec["parameters"].sort(
                    key=lambda p: (p["in"], not p["required"], p["name"])
                )

        # order definitions alphabetically by dict key
        swagger_dict["definitions"] = sort_dict(swagger_dict["definitions"])

**Comment by sklump** [comment]
I can also find some time to look at this today

**Comment by sklump** [comment]
Do you need me to sort paths too? I see that server startup only sorts the values therein explicitly.

**Comment by jcourt562** [comment]
@sklump yes I think that is why @ianco is seeing different output when he runs it to me.  I really think this must be due to simple memory, cpu differences causing order differences on "paths" as I run it with different ACA-py versions and don't see any unexpected changes.

Thanks !

**Comment by sklump** [comment]
See https://github.com/hyperledger/aries-cloudagent-python/pull/785

**Pull request closed without merging**
