### PR TITLE
refactor: introduce use_did and use_did_method

### PR DESCRIPTION
**Pull request by dbluhm**
This implements #2857. With one modification: rather than having a single parameter `use_did`, I found that the processing became significantly simpler by having a `use_did` and `use_did_method` parameter. Hopefully that's an acceptable trade off.

WIP: Currently, just the updates to the did exchange routes have been made. Working through the OOB route updates now. Wanted to open early for feedback.

### CODE REVIEW

**Review by amanji — COMMENTED** [review]
LGTM so far. Some nice cleanup

**Comment by dbluhm** [comment]
Quick update, I took a stab at wrangling the logic of the `create_invitation` method on the OOB manager by introducing a separate class for the purpose. Felt like overkill but the more I leaned into the approach, the clearer to me that the logic is rather complex and having it be split up this way might help. Interested in feedback if anyone has any.

**Comment by dbluhm** [comment]
https://github.com/hyperledger/aries-cloudagent-python/actions/runs/8542753211/job/23405071552?pr=2862#step:3:31413

I think this test failure is unrelated so I'll focus on fixing unit tests first and removing the emit flags officially.

**Comment by swcurran** [comment]
Yes — we are getting this error too often. Pretty sure it is that the DID Seed is not random enough — we keep reusing DIDs used in earlier tests...

**Comment by dbluhm** [comment]
Quick note that with the removal of the `--emit-did-peer-4` and `--emit-did-peer-2` flags, I believe that would mean that the AATH tests recently added for qualified DIDs might need to be updated since those tests depend on using these flags.

**Comment by dbluhm** [comment]
I was seeing test failures that I was not certain were related to my changes here so I went ahead and fixed #2855 in 62744c1

**Comment by dbluhm** [comment]
Interop testing is looking pretty good. I have some small issues to sort out with backwards compat still (my respond-in-kind for the message version is a little wonky) but should be wrapping up soon.

**Comment by dbluhm** [comment]
This is ready for review!

**Review by ianco — DISMISSED** [review]
LGTM.  Are there any docs we need to update?

**Comment by dbluhm** [comment]
Good point! I'll see if I can toss in a quick doc update somewhere

**Comment by dbluhm** [comment]
As I was writing the docs, I realized there is one case I overlooked: when the inviter creates an invite with didexchage/1.1 only and the invitee supports 1.1, it is still sending an unqualified DID in a 1.1 message if the invitee accepts the invitation without specifying a `use_did_method`. I believe it would be preferable for the invitee to automatically prefer using `did:peer:4` in this case. I'll go ahead and make that tweak but open to thoughts if there are any.

**Review by jamshale — DISMISSED** [review]
LGTM!

**Comment by dbluhm** [comment]
@ianco @jamshale I made a couple of fixes and added a new doc outlining use of qualified DIDs in ACA-Py, with details on OOB and DID Exchange

**Review by jamshale — APPROVED** [review]

**Review by ianco — APPROVED** [review]

**Comment by swcurran** [comment]
@dbluhm — are you happy that this is ready to merge?  If so — we can push 0.12.0-rc3 out.

**Comment by dbluhm** [comment]
Yep, ready! I was half keeping an eye on the integration tests just to be sure but my testing indicates that it should be fine

**Pull request merged**
