### PR TITLE
Feat: Upgrade from tags and fix issue with legacy IssuerRevRegRecords [<=`v0.5.2`]

### LINKED ISSUE #2485: ACA-Py 0.10.1 and 0.10.2-rc0 - Errors when calling /revocation/registries/created and /revocation/registry/{rev_reg_id}/fix-revocation-entry-state
To clarify this issue appears to be specific to an agent that has been upgraded from `py36-1.16-1_1.0.0-rc0` to `0.10.1` prior to upgrade to `0.10.2-rc0`.  The same error(s) occur in 0.10.1 and 0.10.2-rc0.  An agent upgraded from `py36-1.16-1_1.0.0-rc0` straight to `0.10.2-rc0` does not appear to be affected.

Scenario:
- LSBC issuer in `dev` upgraded from `py36-1.16-1_1.0.0-rc0` to `0.10.1`, and then to `0.10.2-rc0` is having this issue.
- LSBC issuer in `test` upgraded from `py36-1.16-1_1.0.0-rc0` to `0.10.2-rc0` - the calls work as expected.

[lsbc-dev-0.10.1.log](https://github.com/hyperledger/aries-cloudagent-python/files/12560346/lsbc-dev-0.10.1.log)
[lsbc-dev-0.10.2-rc0.log](https://github.com/hyperledger/aries-cloudagent-python/files/12560348/lsbc-dev-0.10.2-rc0.log)

### PR DESCRIPTION
**Pull request by shaangill025**
- resolve #2485

### CODE REVIEW

**Comment by WadeBarnes** [comment]
I'd like to have this change in a separate release from `0.10.2` (https://github.com/hyperledger/aries-cloudagent-python/issues/2479) as I think it's important to get those changes out first.  I can build a pre-release image off this PR and use that for testing with the affected LSBC agent instance.

**Comment by swcurran** [comment]
Definitely separate from 0.10.2. 0.10.2 is a patch release with two cherry picked PRs from main. This will go into what is likely 0.11.x when merged.

**Comment by WadeBarnes** [comment]
@esune and @WadeBarnes to perform some testing before this gets merged.

**Comment by WadeBarnes** [comment]
@esune, [ghcr.io/hyperledger/aries-cloudagent-python:py3.9-indy-1.16.0-0.11.0-pre0-pr2486](https://github.com/hyperledger/aries-cloudagent-python/pkgs/container/aries-cloudagent-python/128038245?tag=py3.9-indy-1.16.0-0.11.0-pre0-pr2486) has been built and contains the changes from this PR.

**Comment by WadeBarnes** [comment]
@shaangill025, Error log from a test run on the LSBC `dev` agent:
```
2023-09-14 18:35:03,161 aries_cloudagent.commands.upgrade ERROR IssuerRevRegRecord b80174a9-4c9f-4899-8227-c2366c19ab15 tagged for fixing issuance_type.
2023-09-14 18:35:03,164 aries_cloudagent.commands.upgrade ERROR IssuerRevRegRecord fccae016-0281-4f92-9b65-8ae16c27bf06 tagged for fixing issuance_type.
2023-09-14 18:35:03,165 aries_cloudagent.commands.upgrade ERROR IssuerRevRegRecord daed197d-c53b-4349-8679-0531a19e0e68 tagged for fixing issuance_type.
2023-09-14 18:35:03,165 aries_cloudagent.commands.upgrade ERROR IssuerRevRegRecord fcc6c90f-7572-426d-aad9-c8e9e43df73c tagged for fixing issuance_type.
2023-09-14 18:35:03,165 aries_cloudagent.commands.upgrade ERROR IssuerRevRegRecord 484a4aef-1d04-41ed-92bc-741633c13ebe tagged for fixing issuance_type.
2023-09-14 18:35:03,165 aries_cloudagent.commands.upgrade ERROR IssuerRevRegRecord 34765ce2-eb81-4895-be10-137a5c364eea tagged for fixing issuance_type.
2023-09-14 18:35:03,166 aries_cloudagent.commands.upgrade ERROR IssuerRevRegRecord ad5e9186-5c7f-48c7-82e8-31437e6d9687 tagged for fixing issuance_type.
2023-09-14 18:35:03,167 aries_cloudagent.commands.upgrade ERROR IssuerRevRegRecord d42ed0a2-f042-4725-969c-09cd3c6febb9 tagged for fixing issuance_type.
2023-09-14 18:35:03,167 aries_cloudagent.commands.upgrade ERROR IssuerRevRegRecord bf4911a5-e20b-4690-8e37-42085d77e269 tagged for fixing issuance_type.
Traceback (most recent call last):
  File "/home/indy/.local/bin/aca-py", line 8, in <module>
    sys.exit(script_main())
  File "/home/indy/.local/lib/python3.9/site-packages/aries_cloudagent/__main__.py", line 69, in script_main
    main(sys.argv)
  File "/home/indy/.local/lib/python3.9/site-packages/aries_cloudagent/__main__.py", line 75, in main
    run(args)
  File "/home/indy/.local/lib/python3.9/site-packages/aries_cloudagent/__main__.py", line 64, in run
    run_command(command, args)
  File "/home/indy/.local/lib/python3.9/site-packages/aries_cloudagent/commands/__init__.py", line 38, in run_command
    module.execute(argv)
  File "/home/indy/.local/lib/python3.9/site-packages/aries_cloudagent/commands/upgrade.py", line 528, in execute
    loop.run_until_complete(upgrade(settings=settings))
  File "/home/indy/.local/lib/python3.9/site-packages/nest_asyncio.py", line 99, in run_until_complete
    return f.result()
  File "/usr/local/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/home/indy/.local/lib/python3.9/site-packages/aries_cloudagent/commands/upgrade.py", line 409, in upgrade
    await _callable(root_profile)
  File "/home/indy/.local/lib/python3.9/site-packages/aries_cloudagent/commands/upgrade.py", line 503, in fix_issue_rev_reg_records
    record = await IssuerRevRegRecord.retrieve_by_id(
  File "/home/indy/.local/lib/python3.9/site-packages/aries_cloudagent/messaging/models/base_record.py", line 234, in retrieve_by_id
    return cls.from_storage(record_id, vals)
  File "/home/indy/.local/lib/python3.9/site-packages/aries_cloudagent/messaging/models/base_record.py", line 118, in from_storage
    return cls(**params)
  File "/home/indy/.local/lib/python3.9/site-packages/aries_cloudagent/revocation/models/issuer_rev_reg_record.py", line 110, in __init__
    super().__init__(
TypeError: __init__() got an unexpected keyword argument 'issuance_type'
```

**Comment by shaangill025** [comment]
@WadeBarnes Should be fixed now, can you give another try?

**Comment by WadeBarnes** [comment]
Test results from the latest changes can be found here (no errors); https://github.com/hyperledger/aries-cloudagent-python/issues/2485#issuecomment-1721360533

**Comment by WadeBarnes** [comment]
@shaangill025, I'm not sure the log messages should be issued at `ERROR` level when they aren't actually errors.

**Comment by WadeBarnes** [comment]
There are still some issues with the calls to `/revocation/registry/{rev_reg_id}/fix-revocation-entry-state` however.  Adding the details to the related ticket.

**Comment by shaangill025** [comment]
@WadeBarnes If re-run the upgrade, are there any log messages related to `IssueRevRegRecord`?

**Comment by WadeBarnes** [comment]
> @WadeBarnes If re-run the upgrade, are there any log messages related to `IssueRevRegRecord`?

No

**Comment by shaangill025** [comment]
> No. No output. I assumes that means it found nothing to do.

Yes, no problematic records with `issuance_type` remain.

**Comment by WadeBarnes** [comment]
Details of another error where added here; https://github.com/hyperledger/aries-cloudagent-python/issues/2485#issuecomment-1721477640.  Not sure if this error is related to this issue or the fix at all.

**Comment by shaangill025** [comment]
@WadeBarnes Can you please test this by calling `fix-revocation-entry-state` against the problematic `rev_reg_ids`?

**Comment by WadeBarnes** [comment]
Encountered a different error.  Details and logs here; https://github.com/hyperledger/aries-cloudagent-python/issues/2485#issuecomment-1725901972

**Comment by WadeBarnes** [comment]
After migrating from Indy to Askar storage the calls to `fix-revocation-entry-state` (with `apply_ledger_update=false`) completed successfully; https://github.com/hyperledger/aries-cloudagent-python/issues/2485#issuecomment-1727931336.

However the the call to `fix-revocation-entry-state` (with `apply_ledger_update=true`) failed;  https://github.com/hyperledger/aries-cloudagent-python/issues/2485#issuecomment-1727944746

**Comment by WadeBarnes** [comment]
New pre-release image created with the latest changes to this PR; https://github.com/hyperledger/aries-cloudagent-python/pkgs/container/aries-cloudagent-python/129813006?tag=py3.9-indy-1.16.0-0.11.0-pr2486-pre3

**Comment by WadeBarnes** [comment]
Latest changes fix the reported issues; https://github.com/hyperledger/aries-cloudagent-python/issues/2485#issuecomment-1728191251

**Comment by WadeBarnes** [comment]
We're going to have LSBC verify their revoke and re-issue workflow still works.

**Comment by WadeBarnes** [comment]
LSBC has competed testing and confirmed things are working; https://github.com/hyperledger/aries-cloudagent-python/issues/2485#issuecomment-1728425461

**Review by WadeBarnes — CHANGES_REQUESTED** [review]
@shaangill025, The only request I have for this PR is for you to clean up the history a bit.

**Review by WadeBarnes — APPROVED** [review]

**Pull request merged**
