### PR TITLE
added documentation for wallet storage databases

### PR DESCRIPTION
**Pull request by chriamue**
- [x] SQlite
- [x] PostgreDB
- [x] Link in other documentation
- [x] Docker Compose example

### CODE REVIEW

**Comment by chriamue** [comment]
Is `wallet-key` used in storage type postgres?

**Comment by TimoGlastra** [comment]
> Is `wallet-key` used in storage type postgres?

Yes!

**Comment by TimoGlastra** [comment]
@swcurran / @ianco might be good to extract all markdown docs into a separate directory to make it a bit more neatly arranged

**Comment by swcurran** [comment]
Agreed... I'll open a separate issue on that and take it on. I'll combine it with the ability to review the docs on the read-the-docs site.  A good chance for a docs review.

**Review by ianco — APPROVED** [review]

**Pull request merged**
