### PR TITLE
Updates for final Release 0.7.3

### PR DESCRIPTION
**Pull request by swcurran**

### CODE REVIEW

**Comment by swcurran** [comment]
@dbluhm -- how are the Indicio tests on 0.7.3-rc0 going?  We'd like to move forward with the final 0.7.3 release if you are ready.  Please let me know.

Thanks!

**Comment by dbluhm** [comment]
All of our tests so far have checked out! I am waiting on a report on mediation for edge devices with 0.7.3rc0 but should be getting that well before EOD tomorrow.

**Comment by dbluhm** [comment]
Mediation testing returned green!

**Comment by swcurran** [comment]
Thanks!

**Comment by swcurran** [comment]
@andrewwhitehead -- still need your official "Okey-Dokey" on the Upgrade command PR #1557 .

**Comment by swcurran** [comment]
@andrewwhitehead -- this is now ready for review.  Please take a look.  Last changes are only to version.py and the final updates to the changelog.

Thanks!

**Review by andrewwhitehead — APPROVED** [review]

**Pull request merged**
